add_library(App STATIC src/App.c)
target_include_directories(App PUBLIC include)

if(EMSCRIPTEN)
    target_compile_options(App PUBLIC "-sUSE_SDL=2")
    target_link_options(App PUBLIC "-sUSE_SDL=2")
else()
    if(WIN32)
        list(APPEND CMAKE_PREFIX_PATH "C:/msys64/ucrt64")
    endif()
    find_package(SDL2 REQUIRED CONFIG)
    target_link_libraries(App PUBLIC SDL2::SDL2)
endif()

if(SFDE_BUILD_TESTS)
    add_executable(App_test tests/test_App.c)
    target_link_libraries(App_test PRIVATE App)
    add_test(NAME App_test COMMAND App_test)
endif()
