# Ghidra headless script to decompile all functions to C
# Run with: analyzeHeadless /tmp proj -import dll -postScript ghidra_decompile.py

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor
import os

OUTPUT_DIR = "/home/micha/DEV/projects/OpenShadowFlare/documentation/"

def run():
    # Use program name for output file
    prog_name = currentProgram.getName().replace(".dll", "").replace(".exe", "")
    output_file = OUTPUT_DIR + prog_name + "_decompiled.c"
    
    decomp = DecompInterface()
    decomp.openProgram(currentProgram)
    
    monitor = ConsoleTaskMonitor()
    
    with open(output_file, "w") as f:
        f.write("/*\n")
        f.write(" * Decompiled from: %s\n" % currentProgram.getName())
        f.write(" * Generated by Ghidra\n")
        f.write(" */\n\n")
        
        # Get all functions
        fm = currentProgram.getFunctionManager()
        funcs = fm.getFunctions(True)  # True = forward direction
        
        count = 0
        for func in funcs:
            if monitor.isCancelled():
                break
            
            # Decompile each function
            results = decomp.decompileFunction(func, 30, monitor)
            
            if results.decompileCompleted():
                code = results.getDecompiledFunction()
                if code:
                    f.write("/*\n * Function: %s\n * Address: %s\n */\n" % (func.getName(), func.getEntryPoint()))
                    f.write(code.getC())
                    f.write("\n\n")
                    count += 1
        
        print("Decompiled %d functions to %s" % (count, output_file))

run()
