#ifndef SFDE_CONFIG_AI_TUNING_H
#define SFDE_CONFIG_AI_TUNING_H




#define AI_TICK_DELTA_MS 16


#define NPC_WANDER_SPEED_WORLD_UNITS_PER_SEC 150

#define NPC_WANDER_PAUSE_TICKS_MIN 180   

#define NPC_WANDER_PAUSE_TICKS_RANGE 300 


#define NPC_WANDER_STUCK_CHECK_TICKS 120            

#define NPC_WANDER_STUCK_MIN_PROGRESS_WORLD_UNITS 5 


#define LIVE_SPAWN_BLOCK1_ADDEND 10000000

#define LIVE_SPAWN_BLOCK2_ADDEND 12000000

#define LIVE_SPAWN_BLOCK3_ADDEND 14000000


#define LIVE_SPAWN_BLOCK2_PARTNER_OFFSET 1000000


#define LIVE_SPAWN_TEMPLATE_CACHE_MAX 128


#define INTERACT_RADIUS_TILES 2

#endif 
