#ifndef SFDE_CONFIG_COMBAT_TUNING_H
#define SFDE_CONFIG_COMBAT_TUNING_H

#define PLAYER_COMBO_LUNGE_PER_PHASE_WORLD_UNITS 49

#define DEATH_FADE_DURATION_FRAMES 120

#define HIT_REACTION_TICKS_PER_TABLE_UNIT 3

#define HIT_REACTION_UNRESOLVED_CHANCE_BONUS_PERCENT 18

#define HIT_REACTION_UNRESOLVED_DURATION_BONUS_UNITS 6

#define HIT_REACTION_MIN_TICKS 15

#define HIT_REACTION_MAX_TICKS 60

#define HIT_REACTION_WOBBLE_DISTANCE_WORLD_UNITS 12

#define PLAYER_SHAKE_DURATION_TICKS 10

#define PLAYER_SHAKE_MAGNITUDE_WORLD_UNITS 14

#define PLAYER_ATTACK_SPEED_BASE 100.0

#define PLAYER_WALK_SPEED_BASE 128.0

#define HIT_CONNECT_FRACTION_PERCENT 40

#define HIT_VFX_TICKS_PER_FRAME 3

#define BLOOD_DECAL_HOLD_TICKS 120 

#define BLOOD_DECAL_FADE_TICKS 60  

#define BLOOD_DECAL_FALL_TICKS 15          

#define BLOOD_DECAL_FALL_START_OFFSET_Y 28 

#define BLOOD_DECAL_BRIGHTEN_TINT 1200

#define BLOOD_DECAL_MAX 16

#define HIT_VFX_VARIANT_COUNT 3

#define LIVE_SPAWN_DEFAULT_MAX_HP 100

#define ATTACK_DAMAGE 30

#define ATTACK_RADIUS_TILES 2 

#define ENEMY_MITIGATION_PLACEHOLDER 0

#define PLAYER_DEFAULT_MAX_HP 100

#define ENEMY_ATTACK_BASE_DAMAGE_PLACEHOLDER 10

#define ENEMY_ATTACK_COOLDOWN_TICKS 60

#define COMBAT_HIT_SOUND_TRACK 6

#define PLAYER_ATTACK_COOLDOWN_TICKS ENEMY_ATTACK_COOLDOWN_TICKS

#define PLAYER_FOOTPRINT_HALF_WIDTH 40

#define ENEMY_ATTACK_APPROACH_PLAYER_HALF_WIDTH 0

#define CCHECK_RANGE_WORLD_UNITS 159

#define ENEMY_GOLD_DROP_CHANCE_PERCENT 10

#define ENEMY_GOLD_MIN 5

#define ENEMY_GOLD_FIND_MULTIPLIER_PERCENT 100

#define GOLD_PILE_CAP 10000

#endif 
