#ifndef SFDE_CONFIG_HUD_TUNING_H
#define SFDE_CONFIG_HUD_TUNING_H




#define WAITING_SHEET_FRAME_PLATE 0  

#define WAITING_SHEET_FRAME_SWORDS 1 


#define LOADING_PLATE_MARGIN_X 8

#define LOADING_PLATE_MARGIN_Y 8


#define LOADING_SCREEN_MIN_TICKS 45


#define HOVER_HIGHLIGHT_TINT 1250


#define CURSOR_SQUARE_NON_HOVER_OPACITY 150

#define CURSOR_SQUARE_HOVER_OPACITY 350

#define CURSOR_SQUARE_COLOR_B 255

#define CURSOR_SQUARE_COLOR_G 255

#define CURSOR_SQUARE_COLOR_R 255

#define CURSOR_SQUARE_OUTLINE_THICKNESS 1


#define HOVER_LABEL_GAP_Y 8

#define HOVER_LABEL_PADDING_X 6

#define HOVER_LABEL_HEIGHT 16

#define HOVER_LABEL_BORDER_COLOR 0, 0, 0 

#define HOVER_NPC_LABEL_FILL 45, 25, 20  

#define HOVER_ENEMY_BAR_FILL 10, 10, 60  


#define PLAYSOUND_AUDIBLE_RANGE_WORLD_UNITS 3000


#define HUD_BAR_FRAME_BACKGROUND 31

#define HUD_BAR_FRAME_HP_FILL 7

#define HUD_HP_TUBE_OFFSET_X 81 

#define HUD_HP_TUBE_OFFSET_Y 13

#define HUD_BAR_FRAME_MP_FILL 10

#define HUD_MP_TUBE_OFFSET_X 106 

#define HUD_MP_TUBE_OFFSET_Y 40


#define HUD_BAR_FRAME_TUBE_SPARKLE 6

#define HUD_TUBE_SPARKLE_PERIOD_TICKS 90


#define HUD_TUBE_SPARKLE_COUNT 4


#define HUD_TUBE_SPARKLE_EDGE_MARGIN 2


#define HUD_BAR_FRAME_PARTNER_HP_GRADIENT 2

#define HUD_BAR_FRAME_PARTNER_HP_LABEL 3

#define HUD_BAR_FRAME_PARTNER_HP_INACTIVE 0

#define HUD_BAR_FRAME_PARTNER_HP_ACTIVE 1

#define HUD_PARTNER_HP_X 1 


#define HUD_PARTNER_HP_Y 393

#define HUD_PARTNER_HP_TAG_X 57

#define HUD_PARTNER_HP_TAG_Y 390

#define HUD_BAR_FRAME_EXP 4


#define HUD_EXP_X 514 


#define HUD_EXP_Y 395


#define HUD_EXP_TRACK_START 15

#define HUD_EXP_TRACK_END 123


#define HUD_BAR_FRAME_TOP_TRIM 32

#define HUD_BAR_FRAME_MENU 33


#define HUD_MENU_X 577 


#define HUD_BAR_FRAME_DIGIT0 21


#define HUD_LV_DIGITS_X 55

#define HUD_LV_DIGITS_Y 53


#define FONT_FRAME_SINGLE_BYTE 0

#define FONT_GLYPHS_PER_ROW 16

#define FONT_CELL_HEIGHT 12

#define FONT_CELL_WIDTH_HALF 6

#define FONT_CELL_WIDTH_FULL 12


#define COMPASS_TEXT_X 106

#define COMPASS_TEXT_Y 32


#define HUD_RUNWALK_ROW_X 359 

#define HUD_RUNWALK_ROW_WIDTH 60

#define HUD_RUNWALK_ROW_HEIGHT 14

#define HUD_RUNWALK_ICON_OFFSET_X 14

#define HUD_RUNWALK_ICON_OFFSET_Y 2

#define HUD_RUNWALK_ICON_WIDTH 7

#define HUD_RUNWALK_ICON_HEIGHT 5

#define HUD_RUN_ROW_Y 37

#define HUD_WALK_ROW_Y 53


#define HUD_BAR_FRAME_RUN_INACTIVE 14

#define HUD_BAR_FRAME_WALK_INACTIVE 15


#define HUD_RUNWALK_WALK_X_OFFSET 8


#define HUD_BAR_FRAME_MAGIC_SLOT_EMPTY 3

#define HUD_BAR_FRAME_MAGIC_SLOT_ATTACK 2

#define MAGIC_SLOT_SIZE 16

#define MAGIC_SLOT_GROUP_SIZE 4 

#define MAGIC_SLOT_GROUP_GAP 5  

#define MAGIC_SLOT_ATTACK_GAP 9 

#define MAGIC_SLOT_ROW_Y 388


#define MAGIC_BAR_SLOT_COUNT (MAGIC_SLOT_GROUP_SIZE * 2) 
#define MAGIC_SLOT_ATTACK_INDEX MAGIC_BAR_SLOT_COUNT     
#define MAGIC_ICON_FRAME_BASE 4  
#define SPELL_ID_TRANSPORT 0     
#define MAGIC_SLOT_SELECTED_SIZE 24 

#define MAGIC_SLOT_ROW_X_DEFAULT 241        

#define MAGIC_SLOT_ROW_X_INVENTORY_OPEN 118 

#define MAGIC_SLOT_ROW_X_MINIMAP_OPEN 348   


#define COMPASS_CENTER_X 50

#define COMPASS_CENTER_Y 38

#define COMPASS_HOLD_TICKS 240 

#define COMPASS_FADE_TICKS 60  

#endif 
