/*
 * Decompiled from: o_RKC_MEMORY.dll
 * Generated by Ghidra
 */

/*
 * Function: RKC_MEMORY
 * Address: 10001000
 */

/* public: __thiscall RKC_MEMORY::RKC_MEMORY(void) */

void __thiscall RKC_MEMORY::RKC_MEMORY(RKC_MEMORY *this)

{
                    /* 0x1000  1  ??0RKC_MEMORY@@QAE@XZ */
  *(undefined4 *)this = 0;
  *(undefined4 *)(this + 4) = 0;
  return;
}



/*
 * Function: ~RKC_MEMORY
 * Address: 10001010
 */

/* public: __thiscall RKC_MEMORY::~RKC_MEMORY(void) */

void __thiscall RKC_MEMORY::~RKC_MEMORY(RKC_MEMORY *this)

{
                    /* 0x1010  2  ??1RKC_MEMORY@@QAE@XZ */
  if (*(HGLOBAL *)(this + 4) != (HGLOBAL)0x0) {
    GlobalFree(*(HGLOBAL *)(this + 4));
    *(undefined4 *)(this + 4) = 0;
  }
  *(undefined4 *)this = 0;
  return;
}



/*
 * Function: Release
 * Address: 10001020
 */

/* public: void __thiscall RKC_MEMORY::Release(void) */

void __thiscall RKC_MEMORY::Release(RKC_MEMORY *this)

{
                    /* 0x1020  9  ?Release@RKC_MEMORY@@QAEXXZ */
  if (*(HGLOBAL *)(this + 4) != (HGLOBAL)0x0) {
    GlobalFree(*(HGLOBAL *)(this + 4));
    *(undefined4 *)(this + 4) = 0;
  }
  *(undefined4 *)this = 0;
  return;
}



/*
 * Function: Allocation
 * Address: 10001040
 */

/* public: char * __thiscall RKC_MEMORY::Allocation(long,int) */

char * __thiscall RKC_MEMORY::Allocation(RKC_MEMORY *this,long param_1,int param_2)

{
  char *pcVar1;
  UINT uFlags;
  
                    /* 0x1040  4  ?Allocation@RKC_MEMORY@@QAEPADJH@Z */
  Release(this);
  if (param_1 < 1) {
    return (char *)0x0;
  }
  if (param_2 == 1) {
    uFlags = 0x40;
  }
  else {
    uFlags = 0;
  }
  pcVar1 = (char *)GlobalAlloc(uFlags,param_1);
  *(char **)(this + 4) = pcVar1;
  if (pcVar1 == (char *)0x0) {
    return (char *)0x0;
  }
  *(long *)this = param_1;
  return pcVar1;
}



/*
 * Function: Copy
 * Address: 10001090
 */

/* public: int __thiscall RKC_MEMORY::Copy(char *,long,long) */

int __thiscall RKC_MEMORY::Copy(RKC_MEMORY *this,char *param_1,long param_2,long param_3)

{
  uint uVar1;
  char *pcVar2;
  
                    /* 0x1090  6  ?Copy@RKC_MEMORY@@QAEHPADJJ@Z */
  if (param_2 < 1) {
    return 0;
  }
  if (*(int *)this - param_3 < param_2) {
    return 0;
  }
  pcVar2 = (char *)(*(int *)(this + 4) + param_3);
  for (uVar1 = (uint)param_2 >> 2; uVar1 != 0; uVar1 = uVar1 - 1) {
    *(undefined4 *)pcVar2 = *(undefined4 *)param_1;
    param_1 = param_1 + 4;
    pcVar2 = pcVar2 + 4;
  }
  for (uVar1 = param_2 & 3; uVar1 != 0; uVar1 = uVar1 - 1) {
    *pcVar2 = *param_1;
    param_1 = param_1 + 1;
    pcVar2 = pcVar2 + 1;
  }
  return 1;
}



/*
 * Function: Clear
 * Address: 100010e0
 */

/* public: int __thiscall RKC_MEMORY::Clear(char,long,long) */

int __thiscall RKC_MEMORY::Clear(RKC_MEMORY *this,char param_1,long param_2,long param_3)

{
  uint uVar1;
  char *pcVar2;
  
                    /* 0x10e0  5  ?Clear@RKC_MEMORY@@QAEHDJJ@Z */
  if (param_2 == 0) {
    return 0;
  }
  if (param_2 < 0) {
    param_2 = *(long *)this;
  }
  if (*(int *)this - param_3 < param_2) {
    return 0;
  }
  pcVar2 = (char *)(*(int *)(this + 4) + param_3);
  for (uVar1 = (uint)param_2 >> 2; uVar1 != 0; uVar1 = uVar1 - 1) {
    *(uint *)pcVar2 = CONCAT22(CONCAT11(param_1,param_1),CONCAT11(param_1,param_1));
    pcVar2 = pcVar2 + 4;
  }
  for (uVar1 = param_2 & 3; uVar1 != 0; uVar1 = uVar1 - 1) {
    *pcVar2 = param_1;
    pcVar2 = pcVar2 + 1;
  }
  return 1;
}



/*
 * Function: GetSize
 * Address: 10001140
 */

/* public: long __thiscall RKC_MEMORY::GetSize(void) */

long __thiscall RKC_MEMORY::GetSize(RKC_MEMORY *this)

{
                    /* 0x1140  8  ?GetSize@RKC_MEMORY@@QAEJXZ */
  return *(long *)this;
}



/*
 * Function: Get
 * Address: 10001150
 */

/* public: char * __thiscall RKC_MEMORY::Get(void) */

char * __thiscall RKC_MEMORY::Get(RKC_MEMORY *this)

{
                    /* 0x1150  7  ?Get@RKC_MEMORY@@QAEPADXZ */
  return *(char **)(this + 4);
}



/*
 * Function: operator=
 * Address: 10001160
 */

/* public: class RKC_MEMORY & __thiscall RKC_MEMORY::operator=(class RKC_MEMORY const &) */

RKC_MEMORY * __thiscall RKC_MEMORY::operator=(RKC_MEMORY *this,RKC_MEMORY *param_1)

{
                    /* 0x1160  3  ??4RKC_MEMORY@@QAEAAV0@ABV0@@Z */
  *(undefined4 *)this = *(undefined4 *)param_1;
  *(undefined4 *)(this + 4) = *(undefined4 *)(param_1 + 4);
  return this;
}



/*
 * Function: FUN_10001180
 * Address: 10001180
 */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_10001180(undefined4 param_1,int param_2)

{
  int iVar1;
  undefined4 uVar2;
  
  if (param_2 == 1) {
    DAT_10005378 = GetVersion();
    iVar1 = FUN_10001bb4(1);
    if (iVar1 != 0) {
      _DAT_10005384 = DAT_10005378 >> 8 & 0xff;
      _DAT_10005380 = DAT_10005378 & 0xff;
      DAT_10005378 = DAT_10005378 >> 0x10;
      _DAT_1000537c = _DAT_10005380 * 0x100 + _DAT_10005384;
      iVar1 = FUN_10001447();
      if (iVar1 != 0) {
        DAT_100058d8 = GetCommandLineA();
        DAT_10005364 = FUN_10001a82();
        FUN_1000156c();
        FUN_10001835();
        FUN_1000177c();
        FUN_10001329();
        DAT_10005360 = DAT_10005360 + 1;
        goto LAB_10001253;
      }
      FUN_10001bf0();
    }
LAB_100011e0:
    uVar2 = 0;
  }
  else {
    if (param_2 == 0) {
      if (DAT_10005360 < 1) goto LAB_100011e0;
      DAT_10005360 = DAT_10005360 + -1;
      if (DAT_100053b0 == 0) {
        FUN_10001367();
      }
      FUN_10001728();
      FUN_1000149b();
      FUN_10001bf0();
    }
    else if (param_2 == 3) {
      FUN_100014cc((LPVOID)0x0);
    }
LAB_10001253:
    uVar2 = 1;
  }
  return uVar2;
}



/*
 * Function: entry
 * Address: 10001259
 */

int entry(undefined4 param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  int iVar3;
  
  iVar1 = param_2;
  iVar2 = DAT_10005360;
  if (param_2 != 0) {
    if ((param_2 != 1) && (param_2 != 2)) goto LAB_100012a1;
    if ((DAT_100058dc != (code *)0x0) &&
       (iVar2 = (*DAT_100058dc)(param_1,param_2,param_3), iVar2 == 0)) {
      return 0;
    }
    iVar2 = FUN_10001180(param_1,param_2);
  }
  if (iVar2 == 0) {
    return 0;
  }
LAB_100012a1:
  iVar2 = FUN_10001c65();
  if (param_2 == 1) {
    if (iVar2 != 0) {
      return iVar2;
    }
    FUN_10001180(param_1,0);
  }
  if ((param_2 != 0) && (param_2 != 3)) {
    return iVar2;
  }
  iVar3 = FUN_10001180(param_1,param_2);
  param_2 = iVar2;
  if (iVar3 == 0) {
    param_2 = 0;
  }
  if (param_2 != 0) {
    if (DAT_100058dc != (code *)0x0) {
      iVar2 = (*DAT_100058dc)(param_1,iVar1,param_3);
      return iVar2;
    }
    return param_2;
  }
  return 0;
}



/*
 * Function: __amsg_exit
 * Address: 100012f6
 */

/* Library Function - Single Match
    __amsg_exit
   
   Library: Visual Studio 2003 Release */

void __cdecl __amsg_exit(int param_1)

{
  if ((DAT_1000536c == 1) || ((DAT_1000536c == 0 && (DAT_10005370 == 1)))) {
    FUN_10001c6b();
  }
  FUN_10001ca4(param_1);
  (*(code *)PTR___exit_10005030)(0xff);
  return;
}



/*
 * Function: FUN_10001329
 * Address: 10001329
 */

void FUN_10001329(void)

{
  if (DAT_100058d4 != (code *)0x0) {
    (*DAT_100058d4)();
  }
  FUN_1000142d((undefined4 *)&DAT_10005008,(undefined4 *)&DAT_10005010);
  FUN_1000142d((undefined4 *)&DAT_10005000,(undefined4 *)&DAT_10005004);
  return;
}



/*
 * Function: __exit
 * Address: 10001356
 */

/* Library Function - Single Match
    __exit
   
   Library: Visual Studio 2003 Release */

void __cdecl __exit(int _Code)

{
  FUN_10001376(_Code,1,0);
  return;
}



/*
 * Function: FUN_10001367
 * Address: 10001367
 */

void FUN_10001367(void)

{
  FUN_10001376(0,0,1);
  return;
}



/*
 * Function: FUN_10001376
 * Address: 10001376
 */

void __cdecl FUN_10001376(UINT param_1,int param_2,int param_3)

{
  HANDLE hProcess;
  undefined4 *puVar1;
  UINT uExitCode;
  
  FUN_1000141b();
  if (DAT_100053b4 == 1) {
    uExitCode = param_1;
    hProcess = GetCurrentProcess();
    TerminateProcess(hProcess,uExitCode);
  }
  DAT_100053b0 = 1;
  DAT_100053ac = (undefined)param_3;
  if (param_2 == 0) {
    if ((DAT_100058d0 != (undefined4 *)0x0) &&
       (puVar1 = (undefined4 *)(DAT_100058cc - 4), DAT_100058d0 <= puVar1)) {
      do {
        if ((code *)*puVar1 != (code *)0x0) {
          (*(code *)*puVar1)();
        }
        puVar1 = puVar1 + -1;
      } while (DAT_100058d0 <= puVar1);
    }
    FUN_1000142d((undefined4 *)&DAT_10005014,(undefined4 *)&DAT_10005018);
  }
  FUN_1000142d((undefined4 *)&DAT_1000501c,(undefined4 *)&DAT_10005020);
  if (param_3 == 0) {
    DAT_100053b4 = 1;
                    /* WARNING: Subroutine does not return */
    ExitProcess(param_1);
  }
  FUN_10001424();
  return;
}



/*
 * Function: FUN_1000141b
 * Address: 1000141b
 */

void FUN_1000141b(void)

{
  FUN_10001e8c(0xd);
  return;
}



/*
 * Function: FUN_10001424
 * Address: 10001424
 */

void FUN_10001424(void)

{
  FUN_10001eed(0xd);
  return;
}



/*
 * Function: FUN_1000142d
 * Address: 1000142d
 */

void __cdecl FUN_1000142d(undefined4 *param_1,undefined4 *param_2)

{
  for (; param_1 < param_2; param_1 = param_1 + 1) {
    if ((code *)*param_1 != (code *)0x0) {
      (*(code *)*param_1)();
    }
  }
  return;
}



/*
 * Function: FUN_10001447
 * Address: 10001447
 */

undefined4 FUN_10001447(void)

{
  DWORD *lpTlsValue;
  BOOL BVar1;
  DWORD DVar2;
  
  FUN_10001df7();
  DAT_10005034 = TlsAlloc();
  if (DAT_10005034 != 0xffffffff) {
    lpTlsValue = (DWORD *)FUN_10001f02(1,0x74);
    if (lpTlsValue != (DWORD *)0x0) {
      BVar1 = TlsSetValue(DAT_10005034,lpTlsValue);
      if (BVar1 != 0) {
        FUN_100014b9((int)lpTlsValue);
        DVar2 = GetCurrentThreadId();
        lpTlsValue[1] = 0xffffffff;
        *lpTlsValue = DVar2;
        return 1;
      }
    }
  }
  return 0;
}



/*
 * Function: FUN_1000149b
 * Address: 1000149b
 */

void FUN_1000149b(void)

{
  FUN_10001e20();
  if (DAT_10005034 != 0xffffffff) {
    TlsFree(DAT_10005034);
    DAT_10005034 = 0xffffffff;
  }
  return;
}



/*
 * Function: FUN_100014b9
 * Address: 100014b9
 */

void __cdecl FUN_100014b9(int param_1)

{
  *(undefined **)(param_1 + 0x50) = &DAT_100051b0;
  *(undefined4 *)(param_1 + 0x14) = 1;
  return;
}



/*
 * Function: FUN_100014cc
 * Address: 100014cc
 */

void __cdecl FUN_100014cc(LPVOID param_1)

{
  if (DAT_10005034 != 0xffffffff) {
    if ((param_1 != (LPVOID)0x0) || (param_1 = TlsGetValue(DAT_10005034), param_1 != (LPVOID)0x0)) {
      if (*(LPVOID *)((int)param_1 + 0x24) != (LPVOID)0x0) {
        FUN_10001f8f(*(LPVOID *)((int)param_1 + 0x24));
      }
      if (*(LPVOID *)((int)param_1 + 0x28) != (LPVOID)0x0) {
        FUN_10001f8f(*(LPVOID *)((int)param_1 + 0x28));
      }
      if (*(LPVOID *)((int)param_1 + 0x30) != (LPVOID)0x0) {
        FUN_10001f8f(*(LPVOID *)((int)param_1 + 0x30));
      }
      if (*(LPVOID *)((int)param_1 + 0x38) != (LPVOID)0x0) {
        FUN_10001f8f(*(LPVOID *)((int)param_1 + 0x38));
      }
      if (*(LPVOID *)((int)param_1 + 0x40) != (LPVOID)0x0) {
        FUN_10001f8f(*(LPVOID *)((int)param_1 + 0x40));
      }
      if (*(LPVOID *)((int)param_1 + 0x44) != (LPVOID)0x0) {
        FUN_10001f8f(*(LPVOID *)((int)param_1 + 0x44));
      }
      if (*(undefined **)((int)param_1 + 0x50) != &DAT_100051b0) {
        FUN_10001f8f(*(undefined **)((int)param_1 + 0x50));
      }
      FUN_10001f8f(param_1);
    }
    TlsSetValue(DAT_10005034,(LPVOID)0x0);
    return;
  }
  return;
}



/*
 * Function: FUN_1000156c
 * Address: 1000156c
 */

void FUN_1000156c(void)

{
  undefined4 *puVar1;
  undefined4 *puVar2;
  undefined4 *puVar3;
  DWORD DVar4;
  HANDLE hFile;
  UINT *pUVar5;
  int iVar6;
  uint uVar7;
  UINT UVar8;
  UINT UVar9;
  _STARTUPINFOA local_4c;
  byte *local_8;
  
  puVar2 = (undefined4 *)_malloc(0x480);
  if (puVar2 == (undefined4 *)0x0) {
    __amsg_exit(0x1b);
  }
  DAT_100058c0 = 0x20;
  DAT_100057c0 = puVar2;
  for (; puVar2 < DAT_100057c0 + 0x120; puVar2 = puVar2 + 9) {
    *(undefined *)(puVar2 + 1) = 0;
    *puVar2 = 0xffffffff;
    puVar2[2] = 0;
    *(undefined *)((int)puVar2 + 5) = 10;
  }
  GetStartupInfoA(&local_4c);
  if ((local_4c.cbReserved2 != 0) && ((UINT *)local_4c.lpReserved2 != (UINT *)0x0)) {
    UVar8 = *(UINT *)local_4c.lpReserved2;
    pUVar5 = (UINT *)((int)local_4c.lpReserved2 + 4);
    local_8 = (byte *)((int)pUVar5 + UVar8);
    if (0x7ff < (int)UVar8) {
      UVar8 = 0x800;
    }
    UVar9 = UVar8;
    if ((int)DAT_100058c0 < (int)UVar8) {
      puVar2 = &DAT_100057c4;
      do {
        puVar3 = (undefined4 *)_malloc(0x480);
        UVar9 = DAT_100058c0;
        if (puVar3 == (undefined4 *)0x0) break;
        DAT_100058c0 = DAT_100058c0 + 0x20;
        *puVar2 = puVar3;
        puVar1 = puVar3;
        for (; puVar3 < puVar1 + 0x120; puVar3 = puVar3 + 9) {
          *(undefined *)(puVar3 + 1) = 0;
          *puVar3 = 0xffffffff;
          puVar3[2] = 0;
          *(undefined *)((int)puVar3 + 5) = 10;
          puVar1 = (undefined4 *)*puVar2;
        }
        puVar2 = puVar2 + 1;
        UVar9 = UVar8;
      } while ((int)DAT_100058c0 < (int)UVar8);
    }
    uVar7 = 0;
    if (0 < (int)UVar9) {
      do {
        if (((*(HANDLE *)local_8 != (HANDLE)0xffffffff) && ((*(byte *)pUVar5 & 1) != 0)) &&
           (((*(byte *)pUVar5 & 8) != 0 || (DVar4 = GetFileType(*(HANDLE *)local_8), DVar4 != 0))))
        {
          puVar2 = (undefined4 *)((int)(&DAT_100057c0)[(int)uVar7 >> 5] + (uVar7 & 0x1f) * 0x24);
          *puVar2 = *(undefined4 *)local_8;
          *(byte *)(puVar2 + 1) = *(byte *)pUVar5;
        }
        local_8 = local_8 + 4;
        uVar7 = uVar7 + 1;
        pUVar5 = (UINT *)((int)pUVar5 + 1);
      } while ((int)uVar7 < (int)UVar9);
    }
  }
  iVar6 = 0;
  do {
    puVar2 = DAT_100057c0 + iVar6 * 9;
    if (DAT_100057c0[iVar6 * 9] == -1) {
      *(undefined *)(puVar2 + 1) = 0x81;
      if (iVar6 == 0) {
        DVar4 = 0xfffffff6;
      }
      else {
        DVar4 = 0xfffffff5 - (iVar6 != 1);
      }
      hFile = GetStdHandle(DVar4);
      if ((hFile != (HANDLE)0xffffffff) && (DVar4 = GetFileType(hFile), DVar4 != 0)) {
        *puVar2 = hFile;
        if ((DVar4 & 0xff) != 2) {
          if ((DVar4 & 0xff) == 3) {
            *(byte *)(puVar2 + 1) = *(byte *)(puVar2 + 1) | 8;
          }
          goto LAB_10001711;
        }
      }
      *(byte *)(puVar2 + 1) = *(byte *)(puVar2 + 1) | 0x40;
    }
    else {
      *(byte *)(puVar2 + 1) = *(byte *)(puVar2 + 1) | 0x80;
    }
LAB_10001711:
    iVar6 = iVar6 + 1;
    if (2 < iVar6) {
      SetHandleCount(DAT_100058c0);
      return;
    }
  } while( true );
}



/*
 * Function: FUN_10001728
 * Address: 10001728
 */

void FUN_10001728(void)

{
  LPCRITICAL_SECTION lpCriticalSection;
  uint *puVar1;
  uint uVar2;
  
  puVar1 = &DAT_100057c0;
  do {
    uVar2 = *puVar1;
    if (uVar2 != 0) {
      if (uVar2 < uVar2 + 0x480) {
        lpCriticalSection = (LPCRITICAL_SECTION)(uVar2 + 0xc);
        do {
          if (lpCriticalSection[-1].SpinCount != 0) {
            DeleteCriticalSection(lpCriticalSection);
          }
          uVar2 = uVar2 + 0x24;
          lpCriticalSection = (LPCRITICAL_SECTION)&lpCriticalSection[1].OwningThread;
        } while (uVar2 < *puVar1 + 0x480);
      }
      FUN_10001f8f((LPVOID)*puVar1);
      *puVar1 = 0;
    }
    puVar1 = puVar1 + 1;
  } while ((int)puVar1 < 0x100058c0);
  return;
}



/*
 * Function: FUN_1000177c
 * Address: 1000177c
 */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_1000177c(void)

{
  char cVar1;
  size_t sVar2;
  undefined4 *puVar3;
  void *pvVar4;
  int iVar5;
  uint *puVar6;
  
  if (DAT_100058c8 == 0) {
    FUN_100025b3();
  }
  iVar5 = 0;
  for (puVar6 = DAT_10005364; *(char *)puVar6 != '\0'; puVar6 = (uint *)((int)puVar6 + sVar2 + 1)) {
    if (*(char *)puVar6 != '=') {
      iVar5 = iVar5 + 1;
    }
    sVar2 = _strlen((char *)puVar6);
  }
  puVar3 = (undefined4 *)_malloc(iVar5 * 4 + 4);
  _DAT_10005394 = puVar3;
  if (puVar3 == (undefined4 *)0x0) {
    __amsg_exit(9);
  }
  cVar1 = *(char *)DAT_10005364;
  puVar6 = DAT_10005364;
  while (cVar1 != '\0') {
    sVar2 = _strlen((char *)puVar6);
    if (*(char *)puVar6 != '=') {
      pvVar4 = _malloc(sVar2 + 1);
      *puVar3 = pvVar4;
      if (pvVar4 == (void *)0x0) {
        __amsg_exit(9);
      }
      FUN_10002070((uint *)*puVar3,puVar6);
      puVar3 = puVar3 + 1;
    }
    puVar6 = (uint *)((int)puVar6 + sVar2 + 1);
    cVar1 = *(char *)puVar6;
  }
  FUN_10001f8f(DAT_10005364);
  DAT_10005364 = (uint *)0x0;
  *puVar3 = 0;
  _DAT_100058c4 = 1;
  return;
}



/*
 * Function: FUN_10001835
 * Address: 10001835
 */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_10001835(void)

{
  undefined4 *puVar1;
  byte *pbVar2;
  int local_c;
  int local_8;
  
  if (DAT_100058c8 == 0) {
    FUN_100025b3();
  }
  GetModuleFileNameA((HMODULE)0x0,&DAT_100053b8,0x104);
  _DAT_100053a4 = &DAT_100053b8;
  pbVar2 = &DAT_100053b8;
  if (*DAT_100058d8 != 0) {
    pbVar2 = DAT_100058d8;
  }
  FUN_100018ce(pbVar2,(undefined4 *)0x0,(byte *)0x0,&local_8,&local_c);
  puVar1 = (undefined4 *)_malloc(local_c + local_8 * 4);
  if (puVar1 == (undefined4 *)0x0) {
    __amsg_exit(8);
  }
  FUN_100018ce(pbVar2,puVar1,(byte *)(puVar1 + local_8),&local_8,&local_c);
  _DAT_1000538c = puVar1;
  _DAT_10005388 = local_8 + -1;
  return;
}



/*
 * Function: FUN_100018ce
 * Address: 100018ce
 */

void __cdecl FUN_100018ce(byte *param_1,undefined4 *param_2,byte *param_3,int *param_4,int *param_5)

{
  byte bVar1;
  bool bVar2;
  bool bVar3;
  byte *pbVar4;
  byte *pbVar5;
  uint uVar6;
  undefined4 *puVar7;
  
  *param_5 = 0;
  *param_4 = 1;
  if (param_2 != (undefined4 *)0x0) {
    *param_2 = param_3;
    param_2 = param_2 + 1;
  }
  if (*param_1 == 0x22) {
    while( true ) {
      bVar1 = param_1[1];
      pbVar4 = param_1 + 1;
      if ((bVar1 == 0x22) || (bVar1 == 0)) break;
      if ((((&DAT_100056a1)[bVar1] & 4) != 0) && (*param_5 = *param_5 + 1, param_3 != (byte *)0x0))
      {
        *param_3 = *pbVar4;
        param_3 = param_3 + 1;
        pbVar4 = param_1 + 2;
      }
      *param_5 = *param_5 + 1;
      param_1 = pbVar4;
      if (param_3 != (byte *)0x0) {
        *param_3 = *pbVar4;
        param_3 = param_3 + 1;
      }
    }
    *param_5 = *param_5 + 1;
    if (param_3 != (byte *)0x0) {
      *param_3 = 0;
      param_3 = param_3 + 1;
    }
    if (*pbVar4 == 0x22) {
      pbVar4 = param_1 + 2;
    }
  }
  else {
    do {
      *param_5 = *param_5 + 1;
      if (param_3 != (byte *)0x0) {
        *param_3 = *param_1;
        param_3 = param_3 + 1;
      }
      bVar1 = *param_1;
      pbVar4 = param_1 + 1;
      if (((&DAT_100056a1)[bVar1] & 4) != 0) {
        *param_5 = *param_5 + 1;
        if (param_3 != (byte *)0x0) {
          *param_3 = *pbVar4;
          param_3 = param_3 + 1;
        }
        pbVar4 = param_1 + 2;
      }
      if (bVar1 == 0x20) break;
      if (bVar1 == 0) goto LAB_10001979;
      param_1 = pbVar4;
    } while (bVar1 != 9);
    if (bVar1 == 0) {
LAB_10001979:
      pbVar4 = pbVar4 + -1;
    }
    else if (param_3 != (byte *)0x0) {
      param_3[-1] = 0;
    }
  }
  bVar2 = false;
  puVar7 = param_2;
  while (*pbVar4 != 0) {
    for (; (*pbVar4 == 0x20 || (*pbVar4 == 9)); pbVar4 = pbVar4 + 1) {
    }
    if (*pbVar4 == 0) break;
    if (puVar7 != (undefined4 *)0x0) {
      *puVar7 = param_3;
      puVar7 = puVar7 + 1;
      param_2 = puVar7;
    }
    *param_4 = *param_4 + 1;
    while( true ) {
      bVar3 = true;
      uVar6 = 0;
      for (; *pbVar4 == 0x5c; pbVar4 = pbVar4 + 1) {
        uVar6 = uVar6 + 1;
      }
      if (*pbVar4 == 0x22) {
        pbVar5 = pbVar4;
        if ((uVar6 & 1) == 0) {
          if ((!bVar2) || (pbVar5 = pbVar4 + 1, pbVar4[1] != 0x22)) {
            bVar3 = false;
            pbVar5 = pbVar4;
          }
          bVar2 = !bVar2;
          puVar7 = param_2;
        }
        uVar6 = uVar6 >> 1;
        pbVar4 = pbVar5;
      }
      for (; uVar6 != 0; uVar6 = uVar6 - 1) {
        if (param_3 != (byte *)0x0) {
          *param_3 = 0x5c;
          param_3 = param_3 + 1;
        }
        *param_5 = *param_5 + 1;
      }
      bVar1 = *pbVar4;
      if ((bVar1 == 0) || ((!bVar2 && ((bVar1 == 0x20 || (bVar1 == 9)))))) break;
      if (bVar3) {
        if (param_3 == (byte *)0x0) {
          if (((&DAT_100056a1)[bVar1] & 4) != 0) {
            pbVar4 = pbVar4 + 1;
            *param_5 = *param_5 + 1;
          }
        }
        else {
          if (((&DAT_100056a1)[bVar1] & 4) != 0) {
            *param_3 = bVar1;
            param_3 = param_3 + 1;
            pbVar4 = pbVar4 + 1;
            *param_5 = *param_5 + 1;
          }
          *param_3 = *pbVar4;
          param_3 = param_3 + 1;
        }
        *param_5 = *param_5 + 1;
      }
      pbVar4 = pbVar4 + 1;
    }
    if (param_3 != (byte *)0x0) {
      *param_3 = 0;
      param_3 = param_3 + 1;
    }
    *param_5 = *param_5 + 1;
  }
  if (puVar7 != (undefined4 *)0x0) {
    *puVar7 = 0;
  }
  *param_4 = *param_4 + 1;
  return;
}



/*
 * Function: FUN_10001a82
 * Address: 10001a82
 */

LPSTR FUN_10001a82(void)

{
  char cVar1;
  WCHAR WVar2;
  WCHAR *pWVar3;
  WCHAR *pWVar4;
  int iVar5;
  size_t _Size;
  LPSTR pCVar6;
  char *pcVar7;
  LPWCH lpWideCharStr;
  LPCH pCVar9;
  LPSTR local_8;
  char *pcVar8;
  
  lpWideCharStr = (LPWCH)0x0;
  pCVar9 = (LPCH)0x0;
  if (DAT_100054bc == 0) {
    lpWideCharStr = GetEnvironmentStringsW();
    if (lpWideCharStr != (LPWCH)0x0) {
      DAT_100054bc = 1;
LAB_10001ad9:
      if ((lpWideCharStr == (LPWCH)0x0) &&
         (lpWideCharStr = GetEnvironmentStringsW(), lpWideCharStr == (LPWCH)0x0)) {
        return (LPSTR)0x0;
      }
      WVar2 = *lpWideCharStr;
      pWVar4 = lpWideCharStr;
      while (WVar2 != L'\0') {
        do {
          pWVar3 = pWVar4;
          pWVar4 = pWVar3 + 1;
        } while (*pWVar4 != L'\0');
        pWVar4 = pWVar3 + 2;
        WVar2 = *pWVar4;
      }
      iVar5 = ((int)pWVar4 - (int)lpWideCharStr >> 1) + 1;
      _Size = WideCharToMultiByte(0,0,lpWideCharStr,iVar5,(LPSTR)0x0,0,(LPCSTR)0x0,(LPBOOL)0x0);
      local_8 = (LPSTR)0x0;
      if (((_Size != 0) && (pCVar6 = (LPSTR)_malloc(_Size), pCVar6 != (LPSTR)0x0)) &&
         (iVar5 = WideCharToMultiByte(0,0,lpWideCharStr,iVar5,pCVar6,_Size,(LPCSTR)0x0,(LPBOOL)0x0),
         local_8 = pCVar6, iVar5 == 0)) {
        FUN_10001f8f(pCVar6);
        local_8 = (LPSTR)0x0;
      }
      FreeEnvironmentStringsW(lpWideCharStr);
      return local_8;
    }
    pCVar9 = GetEnvironmentStrings();
    if (pCVar9 == (LPCH)0x0) {
      return (LPSTR)0x0;
    }
    DAT_100054bc = 2;
  }
  else {
    if (DAT_100054bc == 1) goto LAB_10001ad9;
    if (DAT_100054bc != 2) {
      return (LPSTR)0x0;
    }
  }
  if ((pCVar9 == (LPCH)0x0) && (pCVar9 = GetEnvironmentStrings(), pCVar9 == (LPCH)0x0)) {
    return (LPSTR)0x0;
  }
  cVar1 = *pCVar9;
  pcVar7 = pCVar9;
  while (cVar1 != '\0') {
    do {
      pcVar8 = pcVar7;
      pcVar7 = pcVar8 + 1;
    } while (*pcVar7 != '\0');
    pcVar7 = pcVar8 + 2;
    cVar1 = *pcVar7;
  }
  pCVar6 = (LPSTR)_malloc((size_t)(pcVar7 + (1 - (int)pCVar9)));
  if (pCVar6 == (LPSTR)0x0) {
    pCVar6 = (LPSTR)0x0;
  }
  else {
    FUN_100025d0((undefined4 *)pCVar6,(undefined4 *)pCVar9,(uint)(pcVar7 + (1 - (int)pCVar9)));
  }
  FreeEnvironmentStringsA(pCVar9);
  return pCVar6;
}



/*
 * Function: FUN_10001bb4
 * Address: 10001bb4
 */

undefined4 __cdecl FUN_10001bb4(int param_1)

{
  int iVar1;
  
  DAT_100057a8 = HeapCreate((uint)(param_1 == 0),0x1000,0);
  if (DAT_100057a8 != (HANDLE)0x0) {
    iVar1 = FUN_10002905();
    if (iVar1 != 0) {
      return 1;
    }
    HeapDestroy(DAT_100057a8);
  }
  return 0;
}



/*
 * Function: FUN_10001bf0
 * Address: 10001bf0
 */

void FUN_10001bf0(void)

{
  int iVar1;
  undefined4 *puVar2;
  
  iVar1 = 0;
  if (0 < DAT_10005578) {
    puVar2 = (undefined4 *)((int)DAT_1000557c + 0xc);
    do {
      VirtualFree((LPVOID)*puVar2,0x100000,0x4000);
      VirtualFree((LPVOID)*puVar2,0,0x8000);
      HeapFree(DAT_100057a8,0,(LPVOID)puVar2[1]);
      puVar2 = puVar2 + 5;
      iVar1 = iVar1 + 1;
    } while (iVar1 < DAT_10005578);
  }
  HeapFree(DAT_100057a8,0,DAT_1000557c);
  HeapDestroy(DAT_100057a8);
  return;
}



/*
 * Function: FUN_10001c65
 * Address: 10001c65
 */

undefined4 FUN_10001c65(void)

{
  return 1;
}



/*
 * Function: FUN_10001c6b
 * Address: 10001c6b
 */

void FUN_10001c6b(void)

{
  if ((DAT_1000536c == 1) || ((DAT_1000536c == 0 && (DAT_10005370 == 1)))) {
    FUN_10001ca4(0xfc);
    if (DAT_100054c0 != (code *)0x0) {
      (*DAT_100054c0)();
    }
    FUN_10001ca4(0xff);
  }
  return;
}



/*
 * Function: FUN_10001ca4
 * Address: 10001ca4
 */

void __cdecl FUN_10001ca4(DWORD param_1)

{
  undefined4 *puVar1;
  DWORD *pDVar2;
  DWORD DVar3;
  size_t sVar4;
  HANDLE hFile;
  int iVar5;
  uint *_Dest;
  undefined auStackY_1e3 [7];
  LPCVOID lpBuffer;
  LPOVERLAPPED lpOverlapped;
  uint local_1a8 [65];
  uint local_a4 [40];
  
  iVar5 = 0;
  pDVar2 = &DAT_10005060;
  do {
    if (param_1 == *pDVar2) break;
    pDVar2 = pDVar2 + 2;
    iVar5 = iVar5 + 1;
  } while ((int)pDVar2 < 0x100050f0);
  if (param_1 == (&DAT_10005060)[iVar5 * 2]) {
    if ((DAT_1000536c == 1) || ((DAT_1000536c == 0 && (DAT_10005370 == 1)))) {
      pDVar2 = &param_1;
      puVar1 = (undefined4 *)(iVar5 * 8 + 0x10005064);
      lpOverlapped = (LPOVERLAPPED)0x0;
      sVar4 = _strlen((char *)*puVar1);
      lpBuffer = (LPCVOID)*puVar1;
      hFile = GetStdHandle(0xfffffff4);
      WriteFile(hFile,lpBuffer,sVar4,pDVar2,lpOverlapped);
    }
    else if (param_1 != 0xfc) {
      DVar3 = GetModuleFileNameA((HMODULE)0x0,(LPSTR)local_1a8,0x104);
      if (DVar3 == 0) {
        FUN_10002070(local_1a8,(uint *)"<program name unknown>");
      }
      _Dest = local_1a8;
      sVar4 = _strlen((char *)local_1a8);
      if (0x3c < sVar4 + 1) {
        sVar4 = _strlen((char *)local_1a8);
        _Dest = (uint *)(auStackY_1e3 + sVar4);
        _strncpy((char *)_Dest,"...",3);
      }
      FUN_10002070(local_a4,(uint *)"Runtime Error!\n\nProgram: ");
      FUN_10002080(local_a4,_Dest);
      FUN_10002080(local_a4,(uint *)&DAT_1000436c);
      FUN_10002080(local_a4,*(uint **)(iVar5 * 8 + 0x10005064));
      auStackY_1e3._3_4_ = 0x10001dc8;
      FUN_1000314e(local_a4,"Microsoft Visual C++ Runtime Library",0x12010);
    }
  }
  return;
}



/*
 * Function: FUN_10001df7
 * Address: 10001df7
 */

void FUN_10001df7(void)

{
  InitializeCriticalSection((LPCRITICAL_SECTION)PTR_DAT_10005134);
  InitializeCriticalSection((LPCRITICAL_SECTION)PTR_DAT_10005124);
  InitializeCriticalSection((LPCRITICAL_SECTION)PTR_DAT_10005114);
  InitializeCriticalSection((LPCRITICAL_SECTION)PTR_DAT_100050f4);
  return;
}



/*
 * Function: FUN_10001e20
 * Address: 10001e20
 */

void FUN_10001e20(void)

{
  undefined **ppuVar1;
  
  ppuVar1 = (undefined **)&DAT_100050f0;
  do {
    if (((((LPCRITICAL_SECTION)*ppuVar1 != (LPCRITICAL_SECTION)0x0) &&
         (ppuVar1 != &PTR_DAT_10005134)) && (ppuVar1 != &PTR_DAT_10005124)) &&
       ((ppuVar1 != &PTR_DAT_10005114 && (ppuVar1 != &PTR_DAT_100050f4)))) {
      DeleteCriticalSection((LPCRITICAL_SECTION)*ppuVar1);
      FUN_10001f8f(*ppuVar1);
    }
    ppuVar1 = ppuVar1 + 1;
  } while ((int)ppuVar1 < 0x100051b0);
  DeleteCriticalSection((LPCRITICAL_SECTION)PTR_DAT_10005114);
  DeleteCriticalSection((LPCRITICAL_SECTION)PTR_DAT_10005124);
  DeleteCriticalSection((LPCRITICAL_SECTION)PTR_DAT_10005134);
  DeleteCriticalSection((LPCRITICAL_SECTION)PTR_DAT_100050f4);
  return;
}



/*
 * Function: FUN_10001e8c
 * Address: 10001e8c
 */

void __cdecl FUN_10001e8c(int param_1)

{
  int *piVar1;
  LPCRITICAL_SECTION lpCriticalSection;
  
  piVar1 = &DAT_100050f0 + param_1;
  if ((&DAT_100050f0)[param_1] == 0) {
    lpCriticalSection = (LPCRITICAL_SECTION)_malloc(0x18);
    if (lpCriticalSection == (LPCRITICAL_SECTION)0x0) {
      __amsg_exit(0x11);
    }
    FUN_10001e8c(0x11);
    if (*piVar1 == 0) {
      InitializeCriticalSection(lpCriticalSection);
      *piVar1 = (int)lpCriticalSection;
    }
    else {
      FUN_10001f8f(lpCriticalSection);
    }
    FUN_10001eed(0x11);
  }
  EnterCriticalSection((LPCRITICAL_SECTION)*piVar1);
  return;
}



/*
 * Function: FUN_10001eed
 * Address: 10001eed
 */

void __cdecl FUN_10001eed(int param_1)

{
  LeaveCriticalSection((LPCRITICAL_SECTION)(&DAT_100050f0)[param_1]);
  return;
}



/*
 * Function: FUN_10001f02
 * Address: 10001f02
 */

int * __cdecl FUN_10001f02(int param_1,int param_2)

{
  int iVar1;
  uint *_Size;
  uint *puVar2;
  int *piVar3;
  
  _Size = (uint *)(param_1 * param_2);
  puVar2 = _Size;
  if (_Size < (uint *)0xffffffe1) {
    if (_Size == (uint *)0x0) {
      puVar2 = (uint *)0x1;
    }
    puVar2 = (uint *)((int)puVar2 + 0xfU & 0xfffffff0);
  }
  do {
    piVar3 = (int *)0x0;
    if (puVar2 < (uint *)0xffffffe1) {
      if (_Size < DAT_10005340 || (int)_Size - (int)DAT_10005340 == 0) {
        FUN_10001e8c(9);
        piVar3 = FUN_10002c99(_Size);
        FUN_10001eed(9);
        if (piVar3 != (int *)0x0) {
          _memset(piVar3,0,(size_t)_Size);
          return piVar3;
        }
      }
      piVar3 = (int *)HeapAlloc(DAT_100057a8,8,(SIZE_T)puVar2);
      if (piVar3 != (int *)0x0) {
        return piVar3;
      }
    }
    if (DAT_1000553c == 0) {
      return piVar3;
    }
    iVar1 = FUN_10003338(puVar2);
  } while (iVar1 != 0);
  return (int *)0x0;
}



/*
 * Function: FUN_10001f8f
 * Address: 10001f8f
 */

void __cdecl FUN_10001f8f(LPVOID param_1)

{
  uint *puVar1;
  
  if (param_1 != (LPVOID)0x0) {
    FUN_10001e8c(9);
    puVar1 = (uint *)FUN_10002943((int)param_1);
    if (puVar1 != (uint *)0x0) {
      FUN_1000296e(puVar1,(uint)param_1);
      FUN_10001eed(9);
      return;
    }
    FUN_10001eed(9);
    HeapFree(DAT_100057a8,0,param_1);
  }
  return;
}



/*
 * Function: _malloc
 * Address: 10001fd7
 */

/* Library Function - Single Match
    _malloc
   
   Library: Visual Studio 2003 Release */

void * __cdecl _malloc(size_t _Size)

{
  void *pvVar1;
  
  pvVar1 = __nh_malloc(_Size,DAT_1000553c);
  return pvVar1;
}



/*
 * Function: __nh_malloc
 * Address: 10001fe9
 */

/* Library Function - Single Match
    __nh_malloc
   
   Library: Visual Studio 2003 Release */

void * __cdecl __nh_malloc(size_t _Size,int _NhFlag)

{
  int *piVar1;
  int iVar2;
  
  if (_Size < 0xffffffe1) {
    do {
      piVar1 = FUN_10002015((uint *)_Size);
      if (piVar1 != (int *)0x0) {
        return piVar1;
      }
      if (_NhFlag == 0) {
        return (void *)0x0;
      }
      iVar2 = FUN_10003338(_Size);
    } while (iVar2 != 0);
  }
  return (void *)0x0;
}



/*
 * Function: FUN_10002015
 * Address: 10002015
 */

int * __cdecl FUN_10002015(uint *param_1)

{
  int *piVar1;
  
  if (param_1 <= DAT_10005340) {
    FUN_10001e8c(9);
    piVar1 = FUN_10002c99(param_1);
    FUN_10001eed(9);
    if (piVar1 != (int *)0x0) {
      return piVar1;
    }
  }
  if (param_1 == (uint *)0x0) {
    param_1 = (uint *)0x1;
  }
  piVar1 = (int *)HeapAlloc(DAT_100057a8,0,(int)param_1 + 0xfU & 0xfffffff0);
  return piVar1;
}



/*
 * Function: FUN_10002070
 * Address: 10002070
 */

uint * __cdecl FUN_10002070(uint *param_1,uint *param_2)

{
  byte bVar1;
  uint uVar2;
  uint uVar3;
  uint *puVar4;
  
  uVar3 = (uint)param_2 & 3;
  puVar4 = param_1;
  while (uVar3 != 0) {
    bVar1 = *(byte *)param_2;
    uVar3 = (uint)bVar1;
    param_2 = (uint *)((int)param_2 + 1);
    if (bVar1 == 0) goto LAB_10002158;
    *(byte *)puVar4 = bVar1;
    puVar4 = (uint *)((int)puVar4 + 1);
    uVar3 = (uint)param_2 & 3;
  }
  do {
    uVar2 = *param_2;
    uVar3 = *param_2;
    param_2 = param_2 + 1;
    if (((uVar2 ^ 0xffffffff ^ uVar2 + 0x7efefeff) & 0x81010100) != 0) {
      if ((char)uVar3 == '\0') {
LAB_10002158:
        *(byte *)puVar4 = (byte)uVar3;
        return param_1;
      }
      if ((char)(uVar3 >> 8) == '\0') {
        *(short *)puVar4 = (short)uVar3;
        return param_1;
      }
      if ((uVar3 & 0xff0000) == 0) {
        *(short *)puVar4 = (short)uVar3;
        *(byte *)((int)puVar4 + 2) = 0;
        return param_1;
      }
      if ((uVar3 & 0xff000000) == 0) {
        *puVar4 = uVar3;
        return param_1;
      }
    }
    *puVar4 = uVar3;
    puVar4 = puVar4 + 1;
  } while( true );
}



/*
 * Function: FUN_10002080
 * Address: 10002080
 */

uint * __cdecl FUN_10002080(uint *param_1,uint *param_2)

{
  byte bVar1;
  uint uVar2;
  uint *puVar3;
  uint uVar4;
  uint *puVar5;
  
  uVar4 = (uint)param_1 & 3;
  puVar3 = param_1;
  while (uVar4 != 0) {
    bVar1 = *(byte *)puVar3;
    puVar3 = (uint *)((int)puVar3 + 1);
    if (bVar1 == 0) goto LAB_100020cf;
    uVar4 = (uint)puVar3 & 3;
  }
  do {
    do {
      puVar5 = puVar3;
      puVar3 = puVar5 + 1;
    } while (((*puVar5 ^ 0xffffffff ^ *puVar5 + 0x7efefeff) & 0x81010100) == 0);
    uVar4 = *puVar5;
    if ((char)uVar4 == '\0') goto LAB_100020e1;
    if ((char)(uVar4 >> 8) == '\0') {
      puVar5 = (uint *)((int)puVar5 + 1);
      goto LAB_100020e1;
    }
    if ((uVar4 & 0xff0000) == 0) {
      puVar5 = (uint *)((int)puVar5 + 2);
      goto LAB_100020e1;
    }
  } while ((uVar4 & 0xff000000) != 0);
LAB_100020cf:
  puVar5 = (uint *)((int)puVar3 + -1);
LAB_100020e1:
  uVar4 = (uint)param_2 & 3;
  while (uVar4 != 0) {
    bVar1 = *(byte *)param_2;
    uVar4 = (uint)bVar1;
    param_2 = (uint *)((int)param_2 + 1);
    if (bVar1 == 0) goto LAB_10002158;
    *(byte *)puVar5 = bVar1;
    puVar5 = (uint *)((int)puVar5 + 1);
    uVar4 = (uint)param_2 & 3;
  }
  do {
    uVar2 = *param_2;
    uVar4 = *param_2;
    param_2 = param_2 + 1;
    if (((uVar2 ^ 0xffffffff ^ uVar2 + 0x7efefeff) & 0x81010100) != 0) {
      if ((char)uVar4 == '\0') {
LAB_10002158:
        *(byte *)puVar5 = (byte)uVar4;
        return param_1;
      }
      if ((char)(uVar4 >> 8) == '\0') {
        *(short *)puVar5 = (short)uVar4;
        return param_1;
      }
      if ((uVar4 & 0xff0000) == 0) {
        *(short *)puVar5 = (short)uVar4;
        *(byte *)((int)puVar5 + 2) = 0;
        return param_1;
      }
      if ((uVar4 & 0xff000000) == 0) {
        *puVar5 = uVar4;
        return param_1;
      }
    }
    *puVar5 = uVar4;
    puVar5 = puVar5 + 1;
  } while( true );
}



/*
 * Function: _strlen
 * Address: 10002160
 */

/* Library Function - Single Match
    _strlen
   
   Libraries: Visual Studio 1998 Debug, Visual Studio 1998 Release */

size_t __cdecl _strlen(char *_Str)

{
  char cVar1;
  uint uVar2;
  uint *puVar3;
  uint *puVar4;
  
  uVar2 = (uint)_Str & 3;
  puVar3 = (uint *)_Str;
  while (uVar2 != 0) {
    cVar1 = *(char *)puVar3;
    puVar3 = (uint *)((int)puVar3 + 1);
    if (cVar1 == '\0') goto LAB_100021b3;
    uVar2 = (uint)puVar3 & 3;
  }
  do {
    do {
      puVar4 = puVar3;
      puVar3 = puVar4 + 1;
    } while (((*puVar4 ^ 0xffffffff ^ *puVar4 + 0x7efefeff) & 0x81010100) == 0);
    uVar2 = *puVar4;
    if ((char)uVar2 == '\0') {
      return (int)puVar4 - (int)_Str;
    }
    if ((char)(uVar2 >> 8) == '\0') {
      return (size_t)((int)puVar4 + (1 - (int)_Str));
    }
    if ((uVar2 & 0xff0000) == 0) {
      return (size_t)((int)puVar4 + (2 - (int)_Str));
    }
  } while ((uVar2 & 0xff000000) != 0);
LAB_100021b3:
  return (size_t)((int)puVar3 + (-1 - (int)_Str));
}



/*
 * Function: FUN_100021db
 * Address: 100021db
 */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 __cdecl FUN_100021db(int param_1)

{
  BYTE *pBVar1;
  byte bVar2;
  byte bVar3;
  UINT CodePage;
  UINT *pUVar4;
  BOOL BVar5;
  uint uVar6;
  uint uVar7;
  BYTE *pBVar8;
  int iVar9;
  byte *pbVar10;
  int iVar11;
  byte *pbVar12;
  undefined4 uVar13;
  undefined4 *puVar14;
  _cpinfo local_1c;
  uint local_8;
  
  FUN_10001e8c(0x19);
  CodePage = FUN_10002388(param_1);
  if (CodePage != DAT_10005580) {
    if (CodePage != 0) {
      iVar11 = 0;
      pUVar4 = &DAT_10005248;
LAB_10002218:
      if (*pUVar4 != CodePage) goto code_r0x1000221c;
      local_8 = 0;
      puVar14 = (undefined4 *)&DAT_100056a0;
      for (iVar9 = 0x40; iVar9 != 0; iVar9 = iVar9 + -1) {
        *puVar14 = 0;
        puVar14 = puVar14 + 1;
      }
      *(undefined *)puVar14 = 0;
      pbVar12 = &DAT_10005258 + iVar11 * 0x30;
      do {
        bVar2 = *pbVar12;
        pbVar10 = pbVar12;
        while ((bVar2 != 0 && (bVar2 = pbVar10[1], bVar2 != 0))) {
          uVar7 = (uint)*pbVar10;
          if (uVar7 <= bVar2) {
            bVar3 = (&DAT_10005240)[local_8];
            do {
              (&DAT_100056a1)[uVar7] = (&DAT_100056a1)[uVar7] | bVar3;
              uVar7 = uVar7 + 1;
            } while (uVar7 <= bVar2);
          }
          pbVar10 = pbVar10 + 2;
          bVar2 = *pbVar10;
        }
        local_8 = local_8 + 1;
        pbVar12 = pbVar12 + 8;
      } while (local_8 < 4);
      _DAT_1000559c = 1;
      DAT_10005580 = CodePage;
      DAT_100057a4 = FUN_100023d2(CodePage);
      DAT_10005590 = (&DAT_1000524c)[iVar11 * 0xc];
      DAT_10005594 = (&DAT_10005250)[iVar11 * 0xc];
      DAT_10005598 = (&DAT_10005254)[iVar11 * 0xc];
      goto LAB_1000236c;
    }
    goto LAB_10002367;
  }
  goto LAB_10002202;
code_r0x1000221c:
  pUVar4 = pUVar4 + 0xc;
  iVar11 = iVar11 + 1;
  if (0x10005337 < (int)pUVar4) goto code_r0x10002227;
  goto LAB_10002218;
code_r0x10002227:
  BVar5 = GetCPInfo(CodePage,&local_1c);
  uVar7 = 1;
  if (BVar5 == 1) {
    DAT_100057a4 = 0;
    puVar14 = (undefined4 *)&DAT_100056a0;
    for (iVar11 = 0x40; iVar11 != 0; iVar11 = iVar11 + -1) {
      *puVar14 = 0;
      puVar14 = puVar14 + 1;
    }
    *(undefined *)puVar14 = 0;
    if (local_1c.MaxCharSize < 2) {
      _DAT_1000559c = 0;
      DAT_10005580 = CodePage;
    }
    else {
      DAT_10005580 = CodePage;
      if (local_1c.LeadByte[0] != '\0') {
        pBVar8 = local_1c.LeadByte + 1;
        do {
          bVar2 = *pBVar8;
          if (bVar2 == 0) break;
          for (uVar6 = (uint)pBVar8[-1]; uVar6 <= bVar2; uVar6 = uVar6 + 1) {
            (&DAT_100056a1)[uVar6] = (&DAT_100056a1)[uVar6] | 4;
          }
          pBVar1 = pBVar8 + 1;
          pBVar8 = pBVar8 + 2;
        } while (*pBVar1 != 0);
      }
      do {
        (&DAT_100056a1)[uVar7] = (&DAT_100056a1)[uVar7] | 8;
        uVar7 = uVar7 + 1;
      } while (uVar7 < 0xff);
      DAT_100057a4 = FUN_100023d2(CodePage);
      _DAT_1000559c = 1;
    }
    DAT_10005590 = 0;
    DAT_10005594 = 0;
    DAT_10005598 = 0;
  }
  else {
    if (DAT_10005528 == 0) {
      uVar13 = 0xffffffff;
      goto LAB_10002379;
    }
LAB_10002367:
    FUN_10002405();
  }
LAB_1000236c:
  FUN_1000242e();
LAB_10002202:
  uVar13 = 0;
LAB_10002379:
  FUN_10001eed(0x19);
  return uVar13;
}



/*
 * Function: FUN_10002388
 * Address: 10002388
 */

int __cdecl FUN_10002388(int param_1)

{
  int iVar1;
  bool bVar2;
  
  if (param_1 == -2) {
    DAT_10005528 = 1;
                    /* WARNING: Could not recover jumptable at 0x100023a2. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    iVar1 = GetOEMCP();
    return iVar1;
  }
  if (param_1 == -3) {
    DAT_10005528 = 1;
                    /* WARNING: Could not recover jumptable at 0x100023b7. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    iVar1 = GetACP();
    return iVar1;
  }
  bVar2 = param_1 == -4;
  if (bVar2) {
    param_1 = DAT_10005558;
  }
  DAT_10005528 = (uint)bVar2;
  return param_1;
}



/*
 * Function: FUN_100023d2
 * Address: 100023d2
 */

undefined4 __cdecl FUN_100023d2(int param_1)

{
  if (param_1 == 0x3a4) {
    return 0x411;
  }
  if (param_1 == 0x3a8) {
    return 0x804;
  }
  if (param_1 == 0x3b5) {
    return 0x412;
  }
  if (param_1 != 0x3b6) {
    return 0;
  }
  return 0x404;
}



/*
 * Function: FUN_10002405
 * Address: 10002405
 */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_10002405(void)

{
  int iVar1;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)&DAT_100056a0;
  for (iVar1 = 0x40; iVar1 != 0; iVar1 = iVar1 + -1) {
    *puVar2 = 0;
    puVar2 = puVar2 + 1;
  }
  *(undefined *)puVar2 = 0;
  DAT_10005580 = 0;
  _DAT_1000559c = 0;
  DAT_100057a4 = 0;
  DAT_10005590 = 0;
  DAT_10005594 = 0;
  DAT_10005598 = 0;
  return;
}



/*
 * Function: FUN_1000242e
 * Address: 1000242e
 */

void FUN_1000242e(void)

{
  BOOL BVar1;
  uint uVar2;
  char cVar3;
  uint uVar4;
  uint uVar5;
  ushort *puVar6;
  undefined uVar7;
  BYTE *pBVar8;
  CHAR *pCVar9;
  WORD local_518 [256];
  WCHAR local_318 [128];
  WCHAR local_218 [128];
  CHAR local_118 [256];
  _cpinfo local_18;
  
  BVar1 = GetCPInfo(DAT_10005580,&local_18);
  if (BVar1 == 1) {
    uVar2 = 0;
    do {
      local_118[uVar2] = (CHAR)uVar2;
      uVar2 = uVar2 + 1;
    } while (uVar2 < 0x100);
    local_118[0] = ' ';
    if (local_18.LeadByte[0] != 0) {
      pBVar8 = local_18.LeadByte + 1;
      do {
        uVar2 = (uint)local_18.LeadByte[0];
        if (uVar2 <= *pBVar8) {
          uVar4 = (*pBVar8 - uVar2) + 1;
          uVar5 = uVar4 >> 2;
          pCVar9 = local_118 + uVar2;
          while (uVar5 != 0) {
            uVar5 = uVar5 - 1;
            builtin_memcpy(pCVar9,"    ",4);
            pCVar9 = pCVar9 + 4;
          }
          for (uVar4 = uVar4 & 3; uVar4 != 0; uVar4 = uVar4 - 1) {
            *pCVar9 = ' ';
            pCVar9 = pCVar9 + 1;
          }
        }
        local_18.LeadByte[0] = pBVar8[1];
        pBVar8 = pBVar8 + 2;
      } while (local_18.LeadByte[0] != 0);
    }
    FUN_100035a2(1,local_118,0x100,local_518,DAT_10005580,DAT_100057a4,0);
    FUN_10003353(DAT_100057a4,0x100,local_118,0x100,local_218,0x100,DAT_10005580,0);
    FUN_10003353(DAT_100057a4,0x200,local_118,0x100,local_318,0x100,DAT_10005580,0);
    uVar2 = 0;
    puVar6 = local_518;
    do {
      if ((*puVar6 & 1) == 0) {
        if ((*puVar6 & 2) != 0) {
          (&DAT_100056a1)[uVar2] = (&DAT_100056a1)[uVar2] | 0x20;
          uVar7 = *(undefined *)((int)local_318 + uVar2);
          goto LAB_1000253a;
        }
        (&DAT_100055a0)[uVar2] = 0;
      }
      else {
        (&DAT_100056a1)[uVar2] = (&DAT_100056a1)[uVar2] | 0x10;
        uVar7 = *(undefined *)((int)local_218 + uVar2);
LAB_1000253a:
        (&DAT_100055a0)[uVar2] = uVar7;
      }
      uVar2 = uVar2 + 1;
      puVar6 = puVar6 + 1;
    } while (uVar2 < 0x100);
  }
  else {
    uVar2 = 0;
    do {
      if ((uVar2 < 0x41) || (0x5a < uVar2)) {
        if ((0x60 < uVar2) && (uVar2 < 0x7b)) {
          (&DAT_100056a1)[uVar2] = (&DAT_100056a1)[uVar2] | 0x20;
          cVar3 = (char)uVar2 + -0x20;
          goto LAB_10002584;
        }
        (&DAT_100055a0)[uVar2] = 0;
      }
      else {
        (&DAT_100056a1)[uVar2] = (&DAT_100056a1)[uVar2] | 0x10;
        cVar3 = (char)uVar2 + ' ';
LAB_10002584:
        (&DAT_100055a0)[uVar2] = cVar3;
      }
      uVar2 = uVar2 + 1;
    } while (uVar2 < 0x100);
  }
  return;
}



/*
 * Function: FUN_100025b3
 * Address: 100025b3
 */

void FUN_100025b3(void)

{
  if (DAT_100058c8 == 0) {
    FUN_100021db(-3);
    DAT_100058c8 = 1;
  }
  return;
}



/*
 * Function: FUN_100025d0
 * Address: 100025d0
 */

undefined4 * __cdecl FUN_100025d0(undefined4 *param_1,undefined4 *param_2,uint param_3)

{
  uint uVar1;
  uint uVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  
  if ((param_2 < param_1) && (param_1 < (undefined4 *)(param_3 + (int)param_2))) {
    puVar3 = (undefined4 *)((param_3 - 4) + (int)param_2);
    puVar4 = (undefined4 *)((param_3 - 4) + (int)param_1);
    if (((uint)puVar4 & 3) == 0) {
      uVar1 = param_3 >> 2;
      uVar2 = param_3 & 3;
      if (7 < uVar1) {
        for (; uVar1 != 0; uVar1 = uVar1 - 1) {
          *puVar4 = *puVar3;
          puVar3 = puVar3 + -1;
          puVar4 = puVar4 + -1;
        }
        switch(uVar2) {
        case 0:
          return param_1;
        case 2:
          goto switchD_10002787_caseD_2;
        case 3:
          goto switchD_10002787_caseD_3;
        }
        goto switchD_10002787_caseD_1;
      }
    }
    else {
      switch(param_3) {
      case 0:
        goto switchD_10002787_caseD_0;
      case 1:
        goto switchD_10002787_caseD_1;
      case 2:
        goto switchD_10002787_caseD_2;
      case 3:
        goto switchD_10002787_caseD_3;
      default:
        uVar1 = param_3 - ((uint)puVar4 & 3);
        switch((uint)puVar4 & 3) {
        case 1:
          uVar2 = uVar1 & 3;
          *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
          puVar3 = (undefined4 *)((int)puVar3 + -1);
          uVar1 = uVar1 >> 2;
          puVar4 = (undefined4 *)((int)puVar4 - 1);
          if (7 < uVar1) {
            for (; uVar1 != 0; uVar1 = uVar1 - 1) {
              *puVar4 = *puVar3;
              puVar3 = puVar3 + -1;
              puVar4 = puVar4 + -1;
            }
            switch(uVar2) {
            case 0:
              return param_1;
            case 2:
              goto switchD_10002787_caseD_2;
            case 3:
              goto switchD_10002787_caseD_3;
            }
            goto switchD_10002787_caseD_1;
          }
          break;
        case 2:
          uVar2 = uVar1 & 3;
          *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
          uVar1 = uVar1 >> 2;
          *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
          puVar3 = (undefined4 *)((int)puVar3 + -2);
          puVar4 = (undefined4 *)((int)puVar4 - 2);
          if (7 < uVar1) {
            for (; uVar1 != 0; uVar1 = uVar1 - 1) {
              *puVar4 = *puVar3;
              puVar3 = puVar3 + -1;
              puVar4 = puVar4 + -1;
            }
            switch(uVar2) {
            case 0:
              return param_1;
            case 2:
              goto switchD_10002787_caseD_2;
            case 3:
              goto switchD_10002787_caseD_3;
            }
            goto switchD_10002787_caseD_1;
          }
          break;
        case 3:
          uVar2 = uVar1 & 3;
          *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
          *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
          uVar1 = uVar1 >> 2;
          *(undefined *)((int)puVar4 + 1) = *(undefined *)((int)puVar3 + 1);
          puVar3 = (undefined4 *)((int)puVar3 + -3);
          puVar4 = (undefined4 *)((int)puVar4 - 3);
          if (7 < uVar1) {
            for (; uVar1 != 0; uVar1 = uVar1 - 1) {
              *puVar4 = *puVar3;
              puVar3 = puVar3 + -1;
              puVar4 = puVar4 + -1;
            }
            switch(uVar2) {
            case 0:
              return param_1;
            case 2:
              goto switchD_10002787_caseD_2;
            case 3:
              goto switchD_10002787_caseD_3;
            }
            goto switchD_10002787_caseD_1;
          }
        }
      }
    }
    switch(uVar1) {
    case 7:
      puVar4[7 - uVar1] = puVar3[7 - uVar1];
    case 6:
      puVar4[6 - uVar1] = puVar3[6 - uVar1];
    case 5:
      puVar4[5 - uVar1] = puVar3[5 - uVar1];
    case 4:
      puVar4[4 - uVar1] = puVar3[4 - uVar1];
    case 3:
      puVar4[3 - uVar1] = puVar3[3 - uVar1];
    case 2:
      puVar4[2 - uVar1] = puVar3[2 - uVar1];
    case 1:
      puVar4[1 - uVar1] = puVar3[1 - uVar1];
      puVar3 = puVar3 + -uVar1;
      puVar4 = puVar4 + -uVar1;
    }
    switch(uVar2) {
    case 1:
switchD_10002787_caseD_1:
      *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
      return param_1;
    case 2:
switchD_10002787_caseD_2:
      *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
      *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
      return param_1;
    case 3:
switchD_10002787_caseD_3:
      *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
      *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
      *(undefined *)((int)puVar4 + 1) = *(undefined *)((int)puVar3 + 1);
      return param_1;
    }
switchD_10002787_caseD_0:
    return param_1;
  }
  puVar3 = param_1;
  if (((uint)param_1 & 3) == 0) {
    uVar1 = param_3 >> 2;
    uVar2 = param_3 & 3;
    if (7 < uVar1) {
      for (; uVar1 != 0; uVar1 = uVar1 - 1) {
        *puVar3 = *param_2;
        param_2 = param_2 + 1;
        puVar3 = puVar3 + 1;
      }
      switch(uVar2) {
      case 0:
        return param_1;
      case 2:
        goto switchD_10002605_caseD_2;
      case 3:
        goto switchD_10002605_caseD_3;
      }
      goto switchD_10002605_caseD_1;
    }
  }
  else {
    switch(param_3) {
    case 0:
      goto switchD_10002605_caseD_0;
    case 1:
      goto switchD_10002605_caseD_1;
    case 2:
      goto switchD_10002605_caseD_2;
    case 3:
      goto switchD_10002605_caseD_3;
    default:
      uVar1 = (param_3 - 4) + ((uint)param_1 & 3);
      switch((uint)param_1 & 3) {
      case 1:
        uVar2 = uVar1 & 3;
        *(undefined *)param_1 = *(undefined *)param_2;
        *(undefined *)((int)param_1 + 1) = *(undefined *)((int)param_2 + 1);
        uVar1 = uVar1 >> 2;
        *(undefined *)((int)param_1 + 2) = *(undefined *)((int)param_2 + 2);
        param_2 = (undefined4 *)((int)param_2 + 3);
        puVar3 = (undefined4 *)((int)param_1 + 3);
        if (7 < uVar1) {
          for (; uVar1 != 0; uVar1 = uVar1 - 1) {
            *puVar3 = *param_2;
            param_2 = param_2 + 1;
            puVar3 = puVar3 + 1;
          }
          switch(uVar2) {
          case 0:
            return param_1;
          case 2:
            goto switchD_10002605_caseD_2;
          case 3:
            goto switchD_10002605_caseD_3;
          }
          goto switchD_10002605_caseD_1;
        }
        break;
      case 2:
        uVar2 = uVar1 & 3;
        *(undefined *)param_1 = *(undefined *)param_2;
        uVar1 = uVar1 >> 2;
        *(undefined *)((int)param_1 + 1) = *(undefined *)((int)param_2 + 1);
        param_2 = (undefined4 *)((int)param_2 + 2);
        puVar3 = (undefined4 *)((int)param_1 + 2);
        if (7 < uVar1) {
          for (; uVar1 != 0; uVar1 = uVar1 - 1) {
            *puVar3 = *param_2;
            param_2 = param_2 + 1;
            puVar3 = puVar3 + 1;
          }
          switch(uVar2) {
          case 0:
            return param_1;
          case 2:
            goto switchD_10002605_caseD_2;
          case 3:
            goto switchD_10002605_caseD_3;
          }
          goto switchD_10002605_caseD_1;
        }
        break;
      case 3:
        uVar2 = uVar1 & 3;
        *(undefined *)param_1 = *(undefined *)param_2;
        param_2 = (undefined4 *)((int)param_2 + 1);
        uVar1 = uVar1 >> 2;
        puVar3 = (undefined4 *)((int)param_1 + 1);
        if (7 < uVar1) {
          for (; uVar1 != 0; uVar1 = uVar1 - 1) {
            *puVar3 = *param_2;
            param_2 = param_2 + 1;
            puVar3 = puVar3 + 1;
          }
          switch(uVar2) {
          case 0:
            return param_1;
          case 2:
            goto switchD_10002605_caseD_2;
          case 3:
            goto switchD_10002605_caseD_3;
          }
          goto switchD_10002605_caseD_1;
        }
      }
    }
  }
  switch(uVar1) {
  case 7:
    puVar3[uVar1 - 7] = param_2[uVar1 - 7];
  case 6:
    puVar3[uVar1 - 6] = param_2[uVar1 - 6];
  case 5:
    puVar3[uVar1 - 5] = param_2[uVar1 - 5];
  case 4:
    puVar3[uVar1 - 4] = param_2[uVar1 - 4];
  case 3:
    puVar3[uVar1 - 3] = param_2[uVar1 - 3];
  case 2:
    puVar3[uVar1 - 2] = param_2[uVar1 - 2];
  case 1:
    puVar3[uVar1 - 1] = param_2[uVar1 - 1];
    param_2 = param_2 + uVar1;
    puVar3 = puVar3 + uVar1;
  }
  switch(uVar2) {
  case 1:
switchD_10002605_caseD_1:
    *(undefined *)puVar3 = *(undefined *)param_2;
    return param_1;
  case 2:
switchD_10002605_caseD_2:
    *(undefined *)puVar3 = *(undefined *)param_2;
    *(undefined *)((int)puVar3 + 1) = *(undefined *)((int)param_2 + 1);
    return param_1;
  case 3:
switchD_10002605_caseD_3:
    *(undefined *)puVar3 = *(undefined *)param_2;
    *(undefined *)((int)puVar3 + 1) = *(undefined *)((int)param_2 + 1);
    *(undefined *)((int)puVar3 + 2) = *(undefined *)((int)param_2 + 2);
    return param_1;
  }
switchD_10002605_caseD_0:
  return param_1;
}



/*
 * Function: FUN_10002905
 * Address: 10002905
 */

undefined4 FUN_10002905(void)

{
  DAT_1000557c = HeapAlloc(DAT_100057a8,0,0x140);
  if (DAT_1000557c == (LPVOID)0x0) {
    return 0;
  }
  DAT_10005574 = 0;
  DAT_10005578 = 0;
  DAT_10005570 = DAT_1000557c;
  DAT_10005568 = 0x10;
  return 1;
}



/*
 * Function: FUN_10002943
 * Address: 10002943
 */

uint __cdecl FUN_10002943(int param_1)

{
  uint uVar1;
  
  uVar1 = DAT_1000557c;
  while( true ) {
    if (DAT_1000557c + DAT_10005578 * 0x14 <= uVar1) {
      return 0;
    }
    if ((uint)(param_1 - *(int *)(uVar1 + 0xc)) < 0x100000) break;
    uVar1 = uVar1 + 0x14;
  }
  return uVar1;
}



/*
 * Function: FUN_1000296e
 * Address: 1000296e
 */

void __cdecl FUN_1000296e(uint *param_1,uint param_2)

{
  char *pcVar1;
  uint *puVar2;
  int *piVar3;
  char cVar4;
  uint uVar5;
  int iVar6;
  uint uVar7;
  byte bVar8;
  int *piVar9;
  uint uVar10;
  uint uVar11;
  uint uVar12;
  int local_10;
  
  uVar5 = param_1[4];
  iVar6 = *(int *)(param_2 - 4);
  piVar9 = (int *)(param_2 - 4);
  uVar10 = param_2 - param_1[3] >> 0xf;
  uVar7 = *(uint *)(param_2 - 8);
  local_10 = iVar6 + -1;
  piVar3 = (int *)(uVar10 * 0x204 + 0x144 + uVar5);
  uVar12 = *(uint *)(local_10 + (int)piVar9);
  if ((uVar12 & 1) == 0) {
    param_2 = ((int)uVar12 >> 4) - 1;
    if (0x3f < param_2) {
      param_2 = 0x3f;
    }
    if (*(int *)(iVar6 + 3 + (int)piVar9) == *(int *)(iVar6 + 7 + (int)piVar9)) {
      if (param_2 < 0x20) {
        pcVar1 = (char *)(param_2 + 4 + uVar5);
        uVar11 = ~(0x80000000U >> ((byte)param_2 & 0x1f));
        puVar2 = (uint *)(uVar5 + 0x44 + uVar10 * 4);
        *puVar2 = *puVar2 & uVar11;
        *pcVar1 = *pcVar1 + -1;
        if (*pcVar1 == '\0') {
          *param_1 = *param_1 & uVar11;
        }
      }
      else {
        pcVar1 = (char *)(param_2 + 4 + uVar5);
        uVar11 = ~(0x80000000U >> ((byte)param_2 - 0x20 & 0x1f));
        puVar2 = (uint *)(uVar5 + 0xc4 + uVar10 * 4);
        *puVar2 = *puVar2 & uVar11;
        *pcVar1 = *pcVar1 + -1;
        if (*pcVar1 == '\0') {
          param_1[1] = param_1[1] & uVar11;
        }
      }
    }
    *(undefined4 *)(*(int *)(iVar6 + 7 + (int)piVar9) + 4) =
         *(undefined4 *)(iVar6 + 3 + (int)piVar9);
    local_10 = local_10 + uVar12;
    *(undefined4 *)(*(int *)(iVar6 + 3 + (int)piVar9) + 8) =
         *(undefined4 *)(iVar6 + 7 + (int)piVar9);
  }
  uVar12 = (local_10 >> 4) - 1;
  if (0x3f < uVar12) {
    uVar12 = 0x3f;
  }
  if ((uVar7 & 1) == 0) {
    piVar9 = (int *)((int)piVar9 - uVar7);
    param_2 = ((int)uVar7 >> 4) - 1;
    if (0x3f < param_2) {
      param_2 = 0x3f;
    }
    local_10 = local_10 + uVar7;
    uVar12 = (local_10 >> 4) - 1;
    if (0x3f < uVar12) {
      uVar12 = 0x3f;
    }
    if (param_2 != uVar12) {
      if (piVar9[1] == piVar9[2]) {
        if (param_2 < 0x20) {
          pcVar1 = (char *)(param_2 + 4 + uVar5);
          uVar11 = ~(0x80000000U >> ((byte)param_2 & 0x1f));
          puVar2 = (uint *)(uVar5 + 0x44 + uVar10 * 4);
          *puVar2 = *puVar2 & uVar11;
          *pcVar1 = *pcVar1 + -1;
          if (*pcVar1 == '\0') {
            *param_1 = *param_1 & uVar11;
          }
        }
        else {
          pcVar1 = (char *)(param_2 + 4 + uVar5);
          uVar11 = ~(0x80000000U >> ((byte)param_2 - 0x20 & 0x1f));
          puVar2 = (uint *)(uVar5 + 0xc4 + uVar10 * 4);
          *puVar2 = *puVar2 & uVar11;
          *pcVar1 = *pcVar1 + -1;
          if (*pcVar1 == '\0') {
            param_1[1] = param_1[1] & uVar11;
          }
        }
      }
      *(int *)(piVar9[2] + 4) = piVar9[1];
      *(int *)(piVar9[1] + 8) = piVar9[2];
    }
  }
  if (((uVar7 & 1) != 0) || (param_2 != uVar12)) {
    piVar9[1] = piVar3[uVar12 * 2 + 1];
    piVar9[2] = (int)(piVar3 + uVar12 * 2);
    (piVar3 + uVar12 * 2)[1] = (int)piVar9;
    *(int **)(piVar9[1] + 8) = piVar9;
    if (piVar9[1] == piVar9[2]) {
      cVar4 = *(char *)(uVar12 + 4 + uVar5);
      *(char *)(uVar12 + 4 + uVar5) = cVar4 + '\x01';
      bVar8 = (byte)uVar12;
      if (uVar12 < 0x20) {
        if (cVar4 == '\0') {
          *param_1 = *param_1 | 0x80000000U >> (bVar8 & 0x1f);
        }
        puVar2 = (uint *)(uVar5 + 0x44 + uVar10 * 4);
        *puVar2 = *puVar2 | 0x80000000U >> (bVar8 & 0x1f);
      }
      else {
        if (cVar4 == '\0') {
          param_1[1] = param_1[1] | 0x80000000U >> (bVar8 - 0x20 & 0x1f);
        }
        puVar2 = (uint *)(uVar5 + 0xc4 + uVar10 * 4);
        *puVar2 = *puVar2 | 0x80000000U >> (bVar8 - 0x20 & 0x1f);
      }
    }
  }
  *piVar9 = local_10;
  *(int *)(local_10 + -4 + (int)piVar9) = local_10;
  *piVar3 = *piVar3 + -1;
  uVar5 = DAT_1000556c;
  puVar2 = DAT_10005574;
  if ((*piVar3 == 0) && (uVar5 = uVar10, puVar2 = param_1, DAT_10005574 != (uint *)0x0)) {
    VirtualFree((LPVOID)(DAT_1000556c * 0x8000 + DAT_10005574[3]),0x8000,0x4000);
    DAT_10005574[2] = DAT_10005574[2] | 0x80000000U >> ((byte)DAT_1000556c & 0x1f);
    *(undefined4 *)(DAT_10005574[4] + 0xc4 + DAT_1000556c * 4) = 0;
    *(char *)(DAT_10005574[4] + 0x43) = *(char *)(DAT_10005574[4] + 0x43) + -1;
    if (*(char *)(DAT_10005574[4] + 0x43) == '\0') {
      DAT_10005574[1] = DAT_10005574[1] & 0xfffffffe;
    }
    puVar2 = param_1;
    if (DAT_10005574[2] == 0xffffffff) {
      VirtualFree((LPVOID)DAT_10005574[3],0,0x8000);
      HeapFree(DAT_100057a8,0,(LPVOID)DAT_10005574[4]);
      FUN_100036f0(DAT_10005574,DAT_10005574 + 5,
                   (DAT_10005578 * 0x14 - (int)DAT_10005574) + -0x14 + DAT_1000557c);
      DAT_10005578 = DAT_10005578 + -1;
      if (DAT_10005574 < param_1) {
        param_1 = param_1 + -5;
      }
      DAT_10005570 = DAT_1000557c;
      puVar2 = param_1;
    }
  }
  DAT_10005574 = puVar2;
  DAT_1000556c = uVar5;
  return;
}



/*
 * Function: FUN_10002c99
 * Address: 10002c99
 */

int * __cdecl FUN_10002c99(uint *param_1)

{
  char *pcVar1;
  int *piVar2;
  char cVar3;
  int *piVar4;
  byte bVar5;
  uint uVar6;
  int iVar7;
  uint *puVar8;
  int iVar9;
  int *piVar10;
  uint *puVar11;
  uint *puVar12;
  uint uVar13;
  int iVar14;
  uint local_10;
  uint local_c;
  int local_8;
  
  puVar8 = DAT_1000557c + DAT_10005578 * 5;
  uVar6 = (int)param_1 + 0x17U & 0xfffffff0;
  iVar7 = ((int)((int)param_1 + 0x17U) >> 4) + -1;
  bVar5 = (byte)iVar7;
  if (iVar7 < 0x20) {
    local_10 = 0xffffffff >> (bVar5 & 0x1f);
    local_c = 0xffffffff;
  }
  else {
    local_c = 0xffffffff >> (bVar5 - 0x20 & 0x1f);
    local_10 = 0;
  }
  param_1 = DAT_10005570;
  if (DAT_10005570 < puVar8) {
    do {
      if ((param_1[1] & local_c) != 0 || (*param_1 & local_10) != 0) break;
      param_1 = param_1 + 5;
    } while (param_1 < puVar8);
  }
  puVar11 = DAT_1000557c;
  if (param_1 == puVar8) {
    for (; (puVar11 < DAT_10005570 && ((puVar11[1] & local_c) == 0 && (*puVar11 & local_10) == 0));
        puVar11 = puVar11 + 5) {
    }
    param_1 = puVar11;
    if (puVar11 == DAT_10005570) {
      for (; (puVar11 < puVar8 && (puVar11[2] == 0)); puVar11 = puVar11 + 5) {
      }
      puVar12 = DAT_1000557c;
      param_1 = puVar11;
      if (puVar11 == puVar8) {
        for (; (puVar12 < DAT_10005570 && (puVar12[2] == 0)); puVar12 = puVar12 + 5) {
        }
        param_1 = puVar12;
        if ((puVar12 == DAT_10005570) && (param_1 = FUN_10002fa2(), param_1 == (uint *)0x0)) {
          return (int *)0x0;
        }
      }
      iVar7 = FUN_10003053((int)param_1);
      *(int *)param_1[4] = iVar7;
      if (*(int *)param_1[4] == -1) {
        return (int *)0x0;
      }
    }
  }
  piVar4 = (int *)param_1[4];
  local_8 = *piVar4;
  if ((local_8 == -1) ||
     ((piVar4[local_8 + 0x31] & local_c) == 0 && (piVar4[local_8 + 0x11] & local_10) == 0)) {
    local_8 = 0;
    puVar8 = (uint *)(piVar4 + 0x11);
    if ((piVar4[0x31] & local_c) == 0 && (piVar4[0x11] & local_10) == 0) {
      do {
        puVar11 = puVar8 + 0x21;
        local_8 = local_8 + 1;
        puVar8 = puVar8 + 1;
      } while ((*puVar11 & local_c) == 0 && (local_10 & *puVar8) == 0);
    }
  }
  iVar7 = 0;
  piVar2 = piVar4 + local_8 * 0x81 + 0x51;
  local_10 = piVar4[local_8 + 0x11] & local_10;
  if (local_10 == 0) {
    local_10 = piVar4[local_8 + 0x31] & local_c;
    iVar7 = 0x20;
  }
  for (; -1 < (int)local_10; local_10 = local_10 << 1) {
    iVar7 = iVar7 + 1;
  }
  piVar10 = (int *)piVar2[iVar7 * 2 + 1];
  iVar9 = *piVar10 - uVar6;
  iVar14 = (iVar9 >> 4) + -1;
  if (0x3f < iVar14) {
    iVar14 = 0x3f;
  }
  DAT_10005570 = param_1;
  if (iVar14 != iVar7) {
    if (piVar10[1] == piVar10[2]) {
      if (iVar7 < 0x20) {
        pcVar1 = (char *)((int)piVar4 + iVar7 + 4);
        uVar13 = ~(0x80000000U >> ((byte)iVar7 & 0x1f));
        piVar4[local_8 + 0x11] = uVar13 & piVar4[local_8 + 0x11];
        *pcVar1 = *pcVar1 + -1;
        if (*pcVar1 == '\0') {
          *param_1 = *param_1 & uVar13;
        }
      }
      else {
        pcVar1 = (char *)((int)piVar4 + iVar7 + 4);
        uVar13 = ~(0x80000000U >> ((byte)iVar7 - 0x20 & 0x1f));
        piVar4[local_8 + 0x31] = piVar4[local_8 + 0x31] & uVar13;
        *pcVar1 = *pcVar1 + -1;
        if (*pcVar1 == '\0') {
          param_1[1] = param_1[1] & uVar13;
        }
      }
    }
    *(int *)(piVar10[2] + 4) = piVar10[1];
    *(int *)(piVar10[1] + 8) = piVar10[2];
    if (iVar9 == 0) goto LAB_10002f5f;
    piVar10[1] = piVar2[iVar14 * 2 + 1];
    piVar10[2] = (int)(piVar2 + iVar14 * 2);
    (piVar2 + iVar14 * 2)[1] = (int)piVar10;
    *(int **)(piVar10[1] + 8) = piVar10;
    if (piVar10[1] == piVar10[2]) {
      cVar3 = *(char *)(iVar14 + 4 + (int)piVar4);
      bVar5 = (byte)iVar14;
      if (iVar14 < 0x20) {
        *(char *)(iVar14 + 4 + (int)piVar4) = cVar3 + '\x01';
        if (cVar3 == '\0') {
          *param_1 = *param_1 | 0x80000000U >> (bVar5 & 0x1f);
        }
        piVar4[local_8 + 0x11] = piVar4[local_8 + 0x11] | 0x80000000U >> (bVar5 & 0x1f);
      }
      else {
        *(char *)(iVar14 + 4 + (int)piVar4) = cVar3 + '\x01';
        if (cVar3 == '\0') {
          param_1[1] = param_1[1] | 0x80000000U >> (bVar5 - 0x20 & 0x1f);
        }
        piVar4[local_8 + 0x31] = piVar4[local_8 + 0x31] | 0x80000000U >> (bVar5 - 0x20 & 0x1f);
      }
    }
  }
  if (iVar9 != 0) {
    *piVar10 = iVar9;
    *(int *)(iVar9 + -4 + (int)piVar10) = iVar9;
  }
LAB_10002f5f:
  piVar10 = (int *)((int)piVar10 + iVar9);
  *piVar10 = uVar6 + 1;
  *(uint *)((int)piVar10 + (uVar6 - 4)) = uVar6 + 1;
  iVar7 = *piVar2;
  *piVar2 = iVar7 + 1;
  if (((iVar7 == 0) && (param_1 == DAT_10005574)) && (local_8 == DAT_1000556c)) {
    DAT_10005574 = (uint *)0x0;
  }
  *piVar4 = local_8;
  return piVar10 + 1;
}



/*
 * Function: FUN_10002fa2
 * Address: 10002fa2
 */

undefined4 * FUN_10002fa2(void)

{
  undefined4 *puVar1;
  LPVOID pvVar2;
  
  if (DAT_10005578 == DAT_10005568) {
    pvVar2 = HeapReAlloc(DAT_100057a8,0,DAT_1000557c,(DAT_10005568 * 5 + 0x50) * 4);
    if (pvVar2 == (LPVOID)0x0) {
      return (undefined4 *)0x0;
    }
    DAT_10005568 = DAT_10005568 + 0x10;
    DAT_1000557c = pvVar2;
  }
  puVar1 = (undefined4 *)((int)DAT_1000557c + DAT_10005578 * 0x14);
  pvVar2 = HeapAlloc(DAT_100057a8,8,0x41c4);
  puVar1[4] = pvVar2;
  if (pvVar2 != (LPVOID)0x0) {
    pvVar2 = VirtualAlloc((LPVOID)0x0,0x100000,0x2000,4);
    puVar1[3] = pvVar2;
    if (pvVar2 != (LPVOID)0x0) {
      puVar1[2] = 0xffffffff;
      *puVar1 = 0;
      puVar1[1] = 0;
      DAT_10005578 = DAT_10005578 + 1;
      *(undefined4 *)puVar1[4] = 0xffffffff;
      return puVar1;
    }
    HeapFree(DAT_100057a8,0,(LPVOID)puVar1[4]);
  }
  return (undefined4 *)0x0;
}



/*
 * Function: FUN_10003053
 * Address: 10003053
 */

int __cdecl FUN_10003053(int param_1)

{
  int *piVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  LPVOID pvVar6;
  int *piVar7;
  int iVar8;
  int iVar9;
  int *lpAddress;
  
  iVar3 = *(int *)(param_1 + 0x10);
  iVar9 = 0;
  for (iVar4 = *(int *)(param_1 + 8); -1 < iVar4; iVar4 = iVar4 << 1) {
    iVar9 = iVar9 + 1;
  }
  iVar8 = 0x3f;
  iVar4 = iVar9 * 0x204 + 0x144 + iVar3;
  iVar5 = iVar4;
  do {
    *(int *)(iVar5 + 8) = iVar5;
    *(int *)(iVar5 + 4) = iVar5;
    iVar5 = iVar5 + 8;
    iVar8 = iVar8 + -1;
  } while (iVar8 != 0);
  lpAddress = (int *)(iVar9 * 0x8000 + *(int *)(param_1 + 0xc));
  pvVar6 = VirtualAlloc(lpAddress,0x8000,0x1000,4);
  if (pvVar6 == (LPVOID)0x0) {
    iVar9 = -1;
  }
  else {
    if (lpAddress <= lpAddress + 0x1c00) {
      piVar7 = lpAddress + 4;
      do {
        piVar7[-2] = -1;
        piVar7[0x3fb] = -1;
        piVar7[-1] = 0xff0;
        *piVar7 = (int)(piVar7 + 0x3ff);
        piVar7[1] = (int)(piVar7 + -0x401);
        piVar7[0x3fa] = 0xff0;
        piVar1 = piVar7 + 0x3fc;
        piVar7 = piVar7 + 0x400;
      } while (piVar1 <= lpAddress + 0x1c00);
    }
    *(int **)(iVar4 + 0x1fc) = lpAddress + 3;
    lpAddress[5] = iVar4 + 0x1f8;
    *(int **)(iVar4 + 0x200) = lpAddress + 0x1c03;
    lpAddress[0x1c04] = iVar4 + 0x1f8;
    *(undefined4 *)(iVar3 + 0x44 + iVar9 * 4) = 0;
    *(undefined4 *)(iVar3 + 0xc4 + iVar9 * 4) = 1;
    cVar2 = *(char *)(iVar3 + 0x43);
    *(char *)(iVar3 + 0x43) = cVar2 + '\x01';
    if (cVar2 == '\0') {
      *(uint *)(param_1 + 4) = *(uint *)(param_1 + 4) | 1;
    }
    *(uint *)(param_1 + 8) = *(uint *)(param_1 + 8) & ~(0x80000000U >> ((byte)iVar9 & 0x1f));
  }
  return iVar9;
}



/*
 * Function: FUN_1000314e
 * Address: 1000314e
 */

int __cdecl FUN_1000314e(undefined4 param_1,undefined4 param_2,undefined4 param_3)

{
  HMODULE hModule;
  int iVar1;
  
  iVar1 = 0;
  if (DAT_1000552c == (FARPROC)0x0) {
    hModule = LoadLibraryA("user32.dll");
    if (hModule != (HMODULE)0x0) {
      DAT_1000552c = GetProcAddress(hModule,"MessageBoxA");
      if (DAT_1000552c != (FARPROC)0x0) {
        DAT_10005530 = GetProcAddress(hModule,"GetActiveWindow");
        DAT_10005534 = GetProcAddress(hModule,"GetLastActivePopup");
        goto LAB_1000319d;
      }
    }
    iVar1 = 0;
  }
  else {
LAB_1000319d:
    if (DAT_10005530 != (FARPROC)0x0) {
      iVar1 = (*DAT_10005530)();
      if ((iVar1 != 0) && (DAT_10005534 != (FARPROC)0x0)) {
        iVar1 = (*DAT_10005534)(iVar1);
      }
    }
    iVar1 = (*DAT_1000552c)(iVar1,param_1,param_2,param_3);
  }
  return iVar1;
}



/*
 * Function: _strncpy
 * Address: 100031e0
 */

/* Library Function - Single Match
    _strncpy
   
   Libraries: Visual Studio 1998 Debug, Visual Studio 1998 Release */

char * __cdecl _strncpy(char *_Dest,char *_Source,size_t _Count)

{
  uint uVar1;
  uint uVar2;
  char cVar3;
  uint uVar4;
  uint *puVar5;
  
  if (_Count == 0) {
    return _Dest;
  }
  puVar5 = (uint *)_Dest;
  if (((uint)_Source & 3) != 0) {
    while( true ) {
      cVar3 = *_Source;
      _Source = (char *)((int)_Source + 1);
      *(char *)puVar5 = cVar3;
      puVar5 = (uint *)((int)puVar5 + 1);
      _Count = _Count - 1;
      if (_Count == 0) {
        return _Dest;
      }
      if (cVar3 == '\0') break;
      if (((uint)_Source & 3) == 0) {
        uVar4 = _Count >> 2;
        goto joined_r0x1000321e;
      }
    }
    do {
      if (((uint)puVar5 & 3) == 0) {
        uVar4 = _Count >> 2;
        cVar3 = '\0';
        if (uVar4 == 0) goto LAB_1000325b;
        goto LAB_100032c9;
      }
      *(char *)puVar5 = '\0';
      puVar5 = (uint *)((int)puVar5 + 1);
      _Count = _Count - 1;
    } while (_Count != 0);
    return _Dest;
  }
  uVar4 = _Count >> 2;
  if (uVar4 != 0) {
    do {
      uVar1 = *(uint *)_Source;
      uVar2 = *(uint *)_Source;
      _Source = (char *)((int)_Source + 4);
      if (((uVar1 ^ 0xffffffff ^ uVar1 + 0x7efefeff) & 0x81010100) != 0) {
        if ((char)uVar2 == '\0') {
          *puVar5 = 0;
joined_r0x100032c5:
          while( true ) {
            uVar4 = uVar4 - 1;
            puVar5 = puVar5 + 1;
            if (uVar4 == 0) break;
LAB_100032c9:
            *puVar5 = 0;
          }
          cVar3 = '\0';
          _Count = _Count & 3;
          if (_Count != 0) goto LAB_1000325b;
          return _Dest;
        }
        if ((char)(uVar2 >> 8) == '\0') {
          *puVar5 = uVar2 & 0xff;
          goto joined_r0x100032c5;
        }
        if ((uVar2 & 0xff0000) == 0) {
          *puVar5 = uVar2 & 0xffff;
          goto joined_r0x100032c5;
        }
        if ((uVar2 & 0xff000000) == 0) {
          *puVar5 = uVar2;
          goto joined_r0x100032c5;
        }
      }
      *puVar5 = uVar2;
      puVar5 = puVar5 + 1;
      uVar4 = uVar4 - 1;
joined_r0x1000321e:
    } while (uVar4 != 0);
    _Count = _Count & 3;
    if (_Count == 0) {
      return _Dest;
    }
  }
  do {
    cVar3 = *_Source;
    _Source = (char *)((int)_Source + 1);
    *(char *)puVar5 = cVar3;
    puVar5 = (uint *)((int)puVar5 + 1);
    if (cVar3 == '\0') {
      while (_Count = _Count - 1, _Count != 0) {
LAB_1000325b:
        *(char *)puVar5 = cVar3;
        puVar5 = (uint *)((int)puVar5 + 1);
      }
      return _Dest;
    }
    _Count = _Count - 1;
  } while (_Count != 0);
  return _Dest;
}



/*
 * Function: _memset
 * Address: 100032e0
 */

/* Library Function - Single Match
    _memset
   
   Libraries: Visual Studio 1998 Debug, Visual Studio 1998 Release */

void * __cdecl _memset(void *_Dst,int _Val,size_t _Size)

{
  uint uVar1;
  uint uVar2;
  size_t sVar3;
  uint *puVar4;
  
  if (_Size == 0) {
    return _Dst;
  }
  uVar1 = _Val & 0xff;
  puVar4 = (uint *)_Dst;
  if (3 < _Size) {
    uVar2 = -(int)_Dst & 3;
    sVar3 = _Size;
    if (uVar2 != 0) {
      sVar3 = _Size - uVar2;
      do {
        *(undefined *)puVar4 = (undefined)_Val;
        puVar4 = (uint *)((int)puVar4 + 1);
        uVar2 = uVar2 - 1;
      } while (uVar2 != 0);
    }
    uVar1 = uVar1 * 0x1010101;
    _Size = sVar3 & 3;
    uVar2 = sVar3 >> 2;
    if (uVar2 != 0) {
      for (; uVar2 != 0; uVar2 = uVar2 - 1) {
        *puVar4 = uVar1;
        puVar4 = puVar4 + 1;
      }
      if (_Size == 0) {
        return _Dst;
      }
    }
  }
  do {
    *(char *)puVar4 = (char)uVar1;
    puVar4 = (uint *)((int)puVar4 + 1);
    _Size = _Size - 1;
  } while (_Size != 0);
  return _Dst;
}



/*
 * Function: FUN_10003338
 * Address: 10003338
 */

undefined4 __cdecl FUN_10003338(undefined4 param_1)

{
  int iVar1;
  
  if (DAT_10005538 != (code *)0x0) {
    iVar1 = (*DAT_10005538)(param_1);
    if (iVar1 != 0) {
      return 1;
    }
  }
  return 0;
}



/*
 * Function: FUN_10003353
 * Address: 10003353
 */

int __cdecl
FUN_10003353(LCID param_1,uint param_2,char *param_3,int param_4,LPWSTR param_5,int param_6,
            UINT param_7,int param_8)

{
  int iVar1;
  int iVar2;
  undefined unaff_DI;
  void *local_14;
  undefined *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_100043f0;
  puStack_10 = &LAB_10003b20;
  local_14 = ExceptionList;
  ExceptionList = &local_14;
  if (DAT_10005560 == 0) {
    ExceptionList = &local_14;
    iVar1 = LCMapStringW(0,0x100,L"",1,(LPWSTR)0x0,0);
    if (iVar1 == 0) {
      iVar1 = LCMapStringA(0,0x100,"",1,(LPSTR)0x0,0);
      if (iVar1 == 0) {
        ExceptionList = local_14;
        return 0;
      }
      DAT_10005560 = 2;
    }
    else {
      DAT_10005560 = 1;
    }
  }
  if (0 < param_4) {
    param_4 = FUN_10003577(param_3,param_4);
  }
  if (DAT_10005560 == 2) {
    iVar1 = LCMapStringA(param_1,param_2,param_3,param_4,(LPSTR)param_5,param_6);
    ExceptionList = local_14;
    return iVar1;
  }
  if (DAT_10005560 == 1) {
    if (param_7 == 0) {
      param_7 = DAT_10005558;
    }
    iVar1 = MultiByteToWideChar(param_7,(-(uint)(param_8 != 0) & 8) + 1,param_3,param_4,(LPWSTR)0x0,
                                0);
    if (iVar1 != 0) {
      local_8 = 0;
      FUN_10003c00(unaff_DI);
      local_8 = 0xffffffff;
      if ((&stack0x00000000 != (undefined *)0x3c) &&
         (iVar2 = MultiByteToWideChar(param_7,1,param_3,param_4,(LPWSTR)&stack0xffffffc4,iVar1),
         iVar2 != 0)) {
        iVar2 = LCMapStringW(param_1,param_2,(LPCWSTR)&stack0xffffffc4,iVar1,(LPWSTR)0x0,0);
        if (iVar2 != 0) {
          if ((param_2 & 0x400) == 0) {
            local_8 = 1;
            FUN_10003c00(unaff_DI);
            local_8 = 0xffffffff;
            if (&stack0x00000000 == (undefined *)0x3c) {
              ExceptionList = local_14;
              return 0;
            }
            iVar1 = LCMapStringW(param_1,param_2,(LPCWSTR)&stack0xffffffc4,iVar1,
                                 (LPWSTR)&stack0xffffffc4,iVar2);
            if (iVar1 == 0) {
              ExceptionList = local_14;
              return 0;
            }
            if (param_6 == 0) {
              param_6 = 0;
              param_5 = (LPWSTR)0x0;
            }
            iVar2 = WideCharToMultiByte(param_7,0x220,(LPCWSTR)&stack0xffffffc4,iVar2,(LPSTR)param_5
                                        ,param_6,(LPCSTR)0x0,(LPBOOL)0x0);
            iVar1 = iVar2;
          }
          else {
            if (param_6 == 0) {
              ExceptionList = local_14;
              return iVar2;
            }
            if (param_6 < iVar2) {
              ExceptionList = local_14;
              return 0;
            }
            iVar1 = LCMapStringW(param_1,param_2,(LPCWSTR)&stack0xffffffc4,iVar1,param_5,param_6);
          }
          if (iVar1 != 0) {
            ExceptionList = local_14;
            return iVar2;
          }
        }
      }
    }
  }
  ExceptionList = local_14;
  return 0;
}



/*
 * Function: FUN_10003577
 * Address: 10003577
 */

int __cdecl FUN_10003577(char *param_1,int param_2)

{
  char *pcVar1;
  int iVar2;
  
  pcVar1 = param_1;
  iVar2 = param_2;
  if (param_2 != 0) {
    do {
      iVar2 = iVar2 + -1;
      if (*pcVar1 == '\0') break;
      pcVar1 = pcVar1 + 1;
    } while (iVar2 != 0);
  }
  if (*pcVar1 == '\0') {
    return (int)pcVar1 - (int)param_1;
  }
  return param_2;
}



/*
 * Function: FUN_100035a2
 * Address: 100035a2
 */

BOOL __cdecl
FUN_100035a2(DWORD param_1,LPCSTR param_2,int param_3,LPWORD param_4,UINT param_5,LCID param_6,
            int param_7)

{
  undefined *puVar1;
  BOOL BVar2;
  int iVar3;
  undefined unaff_DI;
  WORD local_20 [2];
  undefined *local_1c;
  void *local_14;
  undefined *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  local_8 = 0xffffffff;
  puStack_c = &DAT_10004408;
  puStack_10 = &LAB_10003b20;
  local_14 = ExceptionList;
  local_1c = &stack0xffffffc8;
  iVar3 = DAT_10005564;
  ExceptionList = &local_14;
  puVar1 = &stack0xffffffc8;
  if (DAT_10005564 == 0) {
    ExceptionList = &local_14;
    BVar2 = GetStringTypeW(1,L"",1,local_20);
    iVar3 = 1;
    puVar1 = local_1c;
    if (BVar2 == 0) {
      BVar2 = GetStringTypeA(0,1,"",1,local_20);
      if (BVar2 == 0) {
        ExceptionList = local_14;
        return 0;
      }
      iVar3 = 2;
      puVar1 = local_1c;
    }
  }
  local_1c = puVar1;
  DAT_10005564 = iVar3;
  if (DAT_10005564 != 2) {
    if (DAT_10005564 == 1) {
      if (param_5 == 0) {
        param_5 = DAT_10005558;
      }
      iVar3 = MultiByteToWideChar(param_5,(-(uint)(param_7 != 0) & 8) + 1,param_2,param_3,
                                  (LPWSTR)0x0,0);
      if (iVar3 != 0) {
        local_8 = 0;
        FUN_10003c00(unaff_DI);
        local_1c = &stack0xffffffc8;
        _memset(&stack0xffffffc8,0,iVar3 * 2);
        local_8 = 0xffffffff;
        if ((&stack0x00000000 != (undefined *)0x38) &&
           (iVar3 = MultiByteToWideChar(param_5,1,param_2,param_3,(LPWSTR)&stack0xffffffc8,iVar3),
           iVar3 != 0)) {
          BVar2 = GetStringTypeW(param_1,(LPCWSTR)&stack0xffffffc8,iVar3,param_4);
          ExceptionList = local_14;
          return BVar2;
        }
      }
    }
    ExceptionList = local_14;
    return 0;
  }
  if (param_6 == 0) {
    param_6 = DAT_10005548;
  }
  BVar2 = GetStringTypeA(param_6,param_1,param_2,param_3,param_4);
  ExceptionList = local_14;
  return BVar2;
}



/*
 * Function: FUN_100036f0
 * Address: 100036f0
 */

undefined4 * __cdecl FUN_100036f0(undefined4 *param_1,undefined4 *param_2,uint param_3)

{
  uint uVar1;
  uint uVar2;
  undefined4 *puVar3;
  undefined4 *puVar4;
  
  if ((param_2 < param_1) && (param_1 < (undefined4 *)(param_3 + (int)param_2))) {
    puVar3 = (undefined4 *)((param_3 - 4) + (int)param_2);
    puVar4 = (undefined4 *)((param_3 - 4) + (int)param_1);
    if (((uint)puVar4 & 3) == 0) {
      uVar1 = param_3 >> 2;
      uVar2 = param_3 & 3;
      if (7 < uVar1) {
        for (; uVar1 != 0; uVar1 = uVar1 - 1) {
          *puVar4 = *puVar3;
          puVar3 = puVar3 + -1;
          puVar4 = puVar4 + -1;
        }
        switch(uVar2) {
        case 0:
          return param_1;
        case 2:
          goto switchD_100038a7_caseD_2;
        case 3:
          goto switchD_100038a7_caseD_3;
        }
        goto switchD_100038a7_caseD_1;
      }
    }
    else {
      switch(param_3) {
      case 0:
        goto switchD_100038a7_caseD_0;
      case 1:
        goto switchD_100038a7_caseD_1;
      case 2:
        goto switchD_100038a7_caseD_2;
      case 3:
        goto switchD_100038a7_caseD_3;
      default:
        uVar1 = param_3 - ((uint)puVar4 & 3);
        switch((uint)puVar4 & 3) {
        case 1:
          uVar2 = uVar1 & 3;
          *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
          puVar3 = (undefined4 *)((int)puVar3 + -1);
          uVar1 = uVar1 >> 2;
          puVar4 = (undefined4 *)((int)puVar4 - 1);
          if (7 < uVar1) {
            for (; uVar1 != 0; uVar1 = uVar1 - 1) {
              *puVar4 = *puVar3;
              puVar3 = puVar3 + -1;
              puVar4 = puVar4 + -1;
            }
            switch(uVar2) {
            case 0:
              return param_1;
            case 2:
              goto switchD_100038a7_caseD_2;
            case 3:
              goto switchD_100038a7_caseD_3;
            }
            goto switchD_100038a7_caseD_1;
          }
          break;
        case 2:
          uVar2 = uVar1 & 3;
          *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
          uVar1 = uVar1 >> 2;
          *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
          puVar3 = (undefined4 *)((int)puVar3 + -2);
          puVar4 = (undefined4 *)((int)puVar4 - 2);
          if (7 < uVar1) {
            for (; uVar1 != 0; uVar1 = uVar1 - 1) {
              *puVar4 = *puVar3;
              puVar3 = puVar3 + -1;
              puVar4 = puVar4 + -1;
            }
            switch(uVar2) {
            case 0:
              return param_1;
            case 2:
              goto switchD_100038a7_caseD_2;
            case 3:
              goto switchD_100038a7_caseD_3;
            }
            goto switchD_100038a7_caseD_1;
          }
          break;
        case 3:
          uVar2 = uVar1 & 3;
          *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
          *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
          uVar1 = uVar1 >> 2;
          *(undefined *)((int)puVar4 + 1) = *(undefined *)((int)puVar3 + 1);
          puVar3 = (undefined4 *)((int)puVar3 + -3);
          puVar4 = (undefined4 *)((int)puVar4 - 3);
          if (7 < uVar1) {
            for (; uVar1 != 0; uVar1 = uVar1 - 1) {
              *puVar4 = *puVar3;
              puVar3 = puVar3 + -1;
              puVar4 = puVar4 + -1;
            }
            switch(uVar2) {
            case 0:
              return param_1;
            case 2:
              goto switchD_100038a7_caseD_2;
            case 3:
              goto switchD_100038a7_caseD_3;
            }
            goto switchD_100038a7_caseD_1;
          }
        }
      }
    }
    switch(uVar1) {
    case 7:
      puVar4[7 - uVar1] = puVar3[7 - uVar1];
    case 6:
      puVar4[6 - uVar1] = puVar3[6 - uVar1];
    case 5:
      puVar4[5 - uVar1] = puVar3[5 - uVar1];
    case 4:
      puVar4[4 - uVar1] = puVar3[4 - uVar1];
    case 3:
      puVar4[3 - uVar1] = puVar3[3 - uVar1];
    case 2:
      puVar4[2 - uVar1] = puVar3[2 - uVar1];
    case 1:
      puVar4[1 - uVar1] = puVar3[1 - uVar1];
      puVar3 = puVar3 + -uVar1;
      puVar4 = puVar4 + -uVar1;
    }
    switch(uVar2) {
    case 1:
switchD_100038a7_caseD_1:
      *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
      return param_1;
    case 2:
switchD_100038a7_caseD_2:
      *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
      *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
      return param_1;
    case 3:
switchD_100038a7_caseD_3:
      *(undefined *)((int)puVar4 + 3) = *(undefined *)((int)puVar3 + 3);
      *(undefined *)((int)puVar4 + 2) = *(undefined *)((int)puVar3 + 2);
      *(undefined *)((int)puVar4 + 1) = *(undefined *)((int)puVar3 + 1);
      return param_1;
    }
switchD_100038a7_caseD_0:
    return param_1;
  }
  puVar3 = param_1;
  if (((uint)param_1 & 3) == 0) {
    uVar1 = param_3 >> 2;
    uVar2 = param_3 & 3;
    if (7 < uVar1) {
      for (; uVar1 != 0; uVar1 = uVar1 - 1) {
        *puVar3 = *param_2;
        param_2 = param_2 + 1;
        puVar3 = puVar3 + 1;
      }
      switch(uVar2) {
      case 0:
        return param_1;
      case 2:
        goto switchD_10003725_caseD_2;
      case 3:
        goto switchD_10003725_caseD_3;
      }
      goto switchD_10003725_caseD_1;
    }
  }
  else {
    switch(param_3) {
    case 0:
      goto switchD_10003725_caseD_0;
    case 1:
      goto switchD_10003725_caseD_1;
    case 2:
      goto switchD_10003725_caseD_2;
    case 3:
      goto switchD_10003725_caseD_3;
    default:
      uVar1 = (param_3 - 4) + ((uint)param_1 & 3);
      switch((uint)param_1 & 3) {
      case 1:
        uVar2 = uVar1 & 3;
        *(undefined *)param_1 = *(undefined *)param_2;
        *(undefined *)((int)param_1 + 1) = *(undefined *)((int)param_2 + 1);
        uVar1 = uVar1 >> 2;
        *(undefined *)((int)param_1 + 2) = *(undefined *)((int)param_2 + 2);
        param_2 = (undefined4 *)((int)param_2 + 3);
        puVar3 = (undefined4 *)((int)param_1 + 3);
        if (7 < uVar1) {
          for (; uVar1 != 0; uVar1 = uVar1 - 1) {
            *puVar3 = *param_2;
            param_2 = param_2 + 1;
            puVar3 = puVar3 + 1;
          }
          switch(uVar2) {
          case 0:
            return param_1;
          case 2:
            goto switchD_10003725_caseD_2;
          case 3:
            goto switchD_10003725_caseD_3;
          }
          goto switchD_10003725_caseD_1;
        }
        break;
      case 2:
        uVar2 = uVar1 & 3;
        *(undefined *)param_1 = *(undefined *)param_2;
        uVar1 = uVar1 >> 2;
        *(undefined *)((int)param_1 + 1) = *(undefined *)((int)param_2 + 1);
        param_2 = (undefined4 *)((int)param_2 + 2);
        puVar3 = (undefined4 *)((int)param_1 + 2);
        if (7 < uVar1) {
          for (; uVar1 != 0; uVar1 = uVar1 - 1) {
            *puVar3 = *param_2;
            param_2 = param_2 + 1;
            puVar3 = puVar3 + 1;
          }
          switch(uVar2) {
          case 0:
            return param_1;
          case 2:
            goto switchD_10003725_caseD_2;
          case 3:
            goto switchD_10003725_caseD_3;
          }
          goto switchD_10003725_caseD_1;
        }
        break;
      case 3:
        uVar2 = uVar1 & 3;
        *(undefined *)param_1 = *(undefined *)param_2;
        param_2 = (undefined4 *)((int)param_2 + 1);
        uVar1 = uVar1 >> 2;
        puVar3 = (undefined4 *)((int)param_1 + 1);
        if (7 < uVar1) {
          for (; uVar1 != 0; uVar1 = uVar1 - 1) {
            *puVar3 = *param_2;
            param_2 = param_2 + 1;
            puVar3 = puVar3 + 1;
          }
          switch(uVar2) {
          case 0:
            return param_1;
          case 2:
            goto switchD_10003725_caseD_2;
          case 3:
            goto switchD_10003725_caseD_3;
          }
          goto switchD_10003725_caseD_1;
        }
      }
    }
  }
  switch(uVar1) {
  case 7:
    puVar3[uVar1 - 7] = param_2[uVar1 - 7];
  case 6:
    puVar3[uVar1 - 6] = param_2[uVar1 - 6];
  case 5:
    puVar3[uVar1 - 5] = param_2[uVar1 - 5];
  case 4:
    puVar3[uVar1 - 4] = param_2[uVar1 - 4];
  case 3:
    puVar3[uVar1 - 3] = param_2[uVar1 - 3];
  case 2:
    puVar3[uVar1 - 2] = param_2[uVar1 - 2];
  case 1:
    puVar3[uVar1 - 1] = param_2[uVar1 - 1];
    param_2 = param_2 + uVar1;
    puVar3 = puVar3 + uVar1;
  }
  switch(uVar2) {
  case 1:
switchD_10003725_caseD_1:
    *(undefined *)puVar3 = *(undefined *)param_2;
    return param_1;
  case 2:
switchD_10003725_caseD_2:
    *(undefined *)puVar3 = *(undefined *)param_2;
    *(undefined *)((int)puVar3 + 1) = *(undefined *)((int)param_2 + 1);
    return param_1;
  case 3:
switchD_10003725_caseD_3:
    *(undefined *)puVar3 = *(undefined *)param_2;
    *(undefined *)((int)puVar3 + 1) = *(undefined *)((int)param_2 + 1);
    *(undefined *)((int)puVar3 + 2) = *(undefined *)((int)param_2 + 2);
    return param_1;
  }
switchD_10003725_caseD_0:
  return param_1;
}



/*
 * Function: __global_unwind2
 * Address: 10003a28
 */

/* Library Function - Single Match
    __global_unwind2
   
   Library: Visual Studio */

void __cdecl __global_unwind2(PVOID param_1)

{
  RtlUnwind(param_1,(PVOID)0x10003a40,(PEXCEPTION_RECORD)0x0,(PVOID)0x0);
  return;
}



/*
 * Function: __local_unwind2
 * Address: 10003a6a
 */

/* Library Function - Single Match
    __local_unwind2
   
   Libraries: Visual Studio 1998 Debug, Visual Studio 1998 Release, Visual Studio 2003 Debug, Visual
   Studio 2003 Release */

void __cdecl __local_unwind2(int param_1,int param_2)

{
  int iVar1;
  int iVar2;
  void *pvStack_1c;
  undefined *puStack_18;
  undefined4 local_14;
  int iStack_10;
  
  iStack_10 = param_1;
  puStack_18 = &LAB_10003a48;
  pvStack_1c = ExceptionList;
  ExceptionList = &pvStack_1c;
  while( true ) {
    iVar1 = *(int *)(param_1 + 8);
    iVar2 = *(int *)(param_1 + 0xc);
    if ((iVar2 == -1) || (iVar2 == param_2)) break;
    local_14 = *(undefined4 *)(iVar1 + iVar2 * 0xc);
    *(undefined4 *)(param_1 + 0xc) = local_14;
    if (*(int *)(iVar1 + 4 + iVar2 * 0xc) == 0) {
      FUN_10003afe();
      (**(code **)(iVar1 + 8 + iVar2 * 0xc))();
    }
  }
  ExceptionList = pvStack_1c;
  return;
}



/*
 * Function: FUN_10003afe
 * Address: 10003afe
 */

void FUN_10003afe(void)

{
  undefined4 in_EAX;
  int unaff_EBP;
  
  DAT_10005358 = *(undefined4 *)(unaff_EBP + 8);
  DAT_10005354 = in_EAX;
  DAT_1000535c = unaff_EBP;
  return;
}



/*
 * Function: FUN_10003bdd
 * Address: 10003bdd
 */

void FUN_10003bdd(int param_1)

{
  __local_unwind2(*(int *)(param_1 + 0x18),*(int *)(param_1 + 0x1c));
  return;
}



/*
 * Function: FUN_10003c00
 * Address: 10003c00
 */

/* WARNING: Unable to track spacebase fully for stack */

void FUN_10003c00(undefined1 param_1)

{
  uint in_EAX;
  undefined1 *puVar1;
  undefined4 unaff_retaddr;
  
  puVar1 = &param_1;
  if (0xfff < in_EAX) {
    do {
      puVar1 = puVar1 + -0x1000;
      in_EAX = in_EAX - 0x1000;
    } while (0xfff < in_EAX);
  }
  *(undefined4 *)(puVar1 + (-4 - in_EAX)) = unaff_retaddr;
  return;
}



/*
 * Function: RtlUnwind
 * Address: 10003c30
 */

void RtlUnwind(PVOID TargetFrame,PVOID TargetIp,PEXCEPTION_RECORD ExceptionRecord,PVOID ReturnValue)

{
                    /* WARNING: Could not recover jumptable at 0x10003c30. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  RtlUnwind(TargetFrame,TargetIp,ExceptionRecord,ReturnValue);
  return;
}



