#ifndef SFDE_CONFIG_ANIM_TUNING_H
#define SFDE_CONFIG_ANIM_TUNING_H




#define TICKS_PER_ANIM_FRAME 2


#define COMPASS_TICKS_PER_ANIM_FRAME 4


#define PLAYER_RUN_CHART 2

#define PLAYER_IDLE_CHART_AXE_BLUNT 0x18  

#define PLAYER_IDLE_CHART_TWO_HANDED 0x19 

#define PLAYER_WALK_CHART_HEAVY 0x1a      

#define PLAYER_RUN_CHART_AXE_BLUNT 0x1b   

#define PLAYER_RUN_CHART_TWO_HANDED 0x1c  


#define PLAYER_ATTACK_CHART_UNARMED 7

#define PLAYER_ATTACK_CHART_ONE_HANDED_SWING1 5 

#define PLAYER_ATTACK_CHART_ONE_HANDED_SWING2 6 


#define PLAYER_ATTACK_CHART_ONE_HANDED_COMBO2 7

#define PLAYER_ATTACK_CHART_ONE_HANDED 8  

#define PLAYER_ATTACK_CHART_AXE_BLUNT 10  

#define PLAYER_ATTACK_CHART_TWO_HANDED 9  

#define PLAYER_ATTACK_CHART_RANGED_4 0x13 

#define PLAYER_ATTACK_CHART_RANGED_5 0x14 


#define PLAYER_ATTACK_CHART_TWO_HANDED_SWING1 15

#define PLAYER_ATTACK_CHART_TWO_HANDED_SWING2 16

#define PLAYER_ATTACK_CHART_TWO_HANDED_COMBO2 17

#define PLAYER_ATTACK_CHART_TWO_HANDED_COMBO3 18


#define PLAYER_ATTACK_CHART_AXE_SWING1 19 

#define PLAYER_ATTACK_CHART_AXE_SWING2 20 

#define PLAYER_ATTACK_CHART_RANGED 10     


#define PLAYER_ATTACK_CHART_AXE_COMBO_WINDUP 21   

#define PLAYER_ATTACK_CHART_AXE_SWING_LOOP 22     

#define PLAYER_ATTACK_CHART_AXE_COMBO_RECOVERY 23 

#define PLAYER_AXE_SPIN_LOOP_REPEAT_COUNT 3       

#define PLAYER_ATTACK_NONDIRECTIONAL_DIRECTION 8  


#define HIT_REACTION_CHART 2


#define NPC_TALK_CHART 2


#define ATTACK_ANIM_TICKS_PER_FRAME 2


#define PLAYER_ATTACK_ANIM_TICKS_PER_FRAME 1.25


#define ENEMY_ATTACK_CHART 4



#define PLAYER_MAX_CELL_BLOCKS 32


#define PLAYER_CAST_CHART_WINDUP 11

#define PLAYER_CAST_CHART_RELEASE 12

#define PLAYER_CAST_ANIM_TICKS_PER_FRAME 2

#define PLAYER_CAST_RELEASE_HOLD_TICKS 12

#endif 
