#ifndef SFDE_CONFIG_MOVEMENT_TUNING_H
#define SFDE_CONFIG_MOVEMENT_TUNING_H



#define CAMERA_SPEED 8 


#define PLAYER_RUN_SPEED 5

#define PLAYER_WALK_SPEED (PLAYER_RUN_SPEED / 2)


#define CLICK_RANGE_DEFAULT_TILE_HEIGHT (1.0 / 3.0)

#define CLICK_RANGE_MIN_TILE_HEIGHT (1.0 / 12.0)

#define CLICK_RANGE_MAX_TILE_HEIGHT 1.0

#define CLICK_RANGE_STEP_TILE_HEIGHT (1.0 / 12.0)


#define SHIELD_INCOMPATIBLE_WEAPON_CLASS_AXE_BLUNT 1

#define SHIELD_INCOMPATIBLE_WEAPON_CLASS_TWO_HANDED 3


#define VISITED_HISTORY_SIZE 64


#define PATHFIND_STUCK_CHECK_TICKS 3600           

#define PATHFIND_STUCK_MIN_PROGRESS_WORLD_UNITS 5 

#define PATHFIND_MAX_WAYPOINTS 64


#define PATHFIND_TARGET_DRIFT_TOLERANCE_WORLD_UNITS 500

#endif 
