#ifndef SFDE_CONFIG_PROGRESSION_TUNING_H
#define SFDE_CONFIG_PROGRESSION_TUNING_H




#define PLAYER_CLASS_HUNTER 5

#define PLAYER_CLASS_WARRIOR 6

#define PLAYER_CLASS_WITCH 9

#define PLAYER_CLASS_MERCENARY 16


#define CLASS_WITCH_USAGE_PCT 19

#define CLASS_HUNTER_USAGE_PCT 29

#define CLASS_WARRIOR_USAGE_PCT 50

#define CLASS_KILL_USAGE_SLOTS 9 

#define PLAYER_LEVEL_CAP 100        

#define TABLE_SPELL_MP_COST 0x10    
#define TABLE_XP_CURVE 0x0D         

#define TABLE_EXP_MULTIPLIER 0x0E   

#define TABLE_PLAYER_BASE_STATS 901 

#define TABLE_PLAYER_GROWTH_BASE 901 


#define LEVELUP_NOTICE_CENTER_TICKS 150

#define LEVELUP_NOTICE_SLIDE_TICKS 30

#define LEVELUP_NOTICE_HOLD_TICKS 210

#define LEVELUP_NOTICE_TOTAL_TICKS \
    (LEVELUP_NOTICE_CENTER_TICKS + LEVELUP_NOTICE_SLIDE_TICKS + LEVELUP_NOTICE_HOLD_TICKS)


#define LEVELUP_NOTICE_PANEL_ALPHA 450

#define LEVELUP_NOTICE_BORDER_ALPHA 650

#endif 
