#ifndef SFDE_CONFIG_UI_WORLD_TUNING_H
#define SFDE_CONFIG_UI_WORLD_TUNING_H




#define DEBUG_ITEM_CYCLE_KIND_WEAPON 0

#define DEBUG_ITEM_CYCLE_KIND_HELMET 1

#define DEBUG_ITEM_CYCLE_KIND_BODY 2

#define DEBUG_ITEM_CYCLE_KIND_BOOTS 3

#define DEBUG_ITEM_CYCLE_KIND_SHIELD 4

#define DEBUG_ITEM_CYCLE_KIND_ACCESSORY 5

#define DEBUG_ITEM_CYCLE_COUNT 6


#define DIALOG_LINE_MAX 512

#define DIALOG_MAX_ROWS 8                

#define DIALOG_LINE_HEIGHT 12            

#define DIALOG_LINE_SAFETY_MAX_WIDTH 560 

#define DIALOG_BUBBLE_PADDING 10

#define DIALOG_BUBBLE_CORNER 9             

#define DIALOG_BUBBLE_BORDER 2             

#define DIALOG_BUBBLE_ANCHOR_GAP_Y 87      

#define DIALOG_BUBBLE_FILL 248, 248, 248   

#define DIALOG_BUBBLE_BORDER_COLOR 0, 0, 0 

#define HUKIDASI_FRAME_TAIL_NPC 4          

#define HUKIDASI_FRAME_TAIL_PARTNER 5      

#define DIALOG_TAIL_OFFSET_X 15            

#define DIALOG_TAIL_OFFSET_Y 3             


#define DIALOG_QUEUE_MAX 8


#define TALKEND_CHAIN_MAX 16


#define QUEST_BANNER_TICKS 600


#define FLOATING_VALUE_MAX 16


#define SCRIPT_EFFECT_MAX 16


#define SCRIPT_EFFECT_TEMPLATE_CACHE_MAX 8


#define DIALOG_OPTION_QUIT_GAP 6


#define MINIMAP_PANEL_X 10

#define MINIMAP_PANEL_Y 10


#define MINIMAP_AREA_NAME_X 40

#define MINIMAP_AREA_NAME_Y 49

#define MINIMAP_PLAYER_LABEL_GAP_Y 10 

#define MINIMAP_PANEL_WIDTH 285

#define MINIMAP_PANEL_HEIGHT 380


#define MINIMAP_CONTENT_Y_OFFSET 60


#define MINIMAP_WINDOW_X 0

#define MINIMAP_WINDOW_Y 0

#define MINIMAP_WINDOW_WIDTH 320

#define MINIMAP_WINDOW_HEIGHT 415

#define MINIMAP_BG_FRAME_TOP 2

#define MINIMAP_BG_FRAME_BOTTOM 1

#define MINIMAP_BG_FRAME_LEFT 65

#define MINIMAP_BG_FRAME_RIGHT 67


#define QUEST_WINDOW_FRAME_BODY 64

#define QUEST_WINDOW_FRAME_LEFT 65

#define QUEST_WINDOW_FRAME_TOP 66

#define QUEST_WINDOW_FRAME_RIGHT 67

#define QUEST_WINDOW_FRAME_BOTTOM 68

#define QUEST_TAB_FRAME_UNSELECTED_BASE 19 

#define QUEST_TAB_FRAME_SELECTED_BASE 29   

#define QUEST_TAB_COUNT 2                  

#define QUEST_TAB_X 296                    

#define QUEST_TAB_Y 8

#define QUEST_TAB_GAP 8


#define QUEST_ICON_FRAME_ACTIVE 0

#define QUEST_ICON_FRAME_COMPLETED 1

#define QUEST_LINE_START_Y 52

#define QUEST_LINE_HEIGHT 24

#define QUEST_LINE_ICON_X 36

#define QUEST_LINE_TEXT_X 55


#define QUEST_TOOLTIP_FRAME_BOTTOM 48

#define QUEST_TOOLTIP_FRAME_TOP 49

#define QUEST_TOOLTIP_FRAME_LEFT 50

#define QUEST_TOOLTIP_FRAME_RIGHT 51


#define ITEM_TOOLTIP_DELAY_TICKS 35


#define ITEM_TOOLTIP_BG_OPACITY 780


#define QUEST_BANNER_Y 46


#define GATE_WINDOW_FRAME_BODY 58

#define GATE_WINDOW_FRAME_ROW_ICON 59

#define GATE_LINE_ICON_X 46

#define GATE_LINE_TEXT_X 70

#define GATE_LINE_START_Y 64

#define GATE_LINE_HEIGHT 30


#define GATE_ROWS_PER_PAGE 10

#define GATE_PAGE_TEXT_Y 372

#define GATE_PAGE_ARROW_Y0 364

#define GATE_PAGE_ARROW_Y1 392

#define GATE_PAGE_PREV_X0 95

#define GATE_PAGE_PREV_X1 150

#define GATE_PAGE_NEXT_X0 190

#define GATE_PAGE_NEXT_X1 245


#define GATE_ICON_FRAME_NORMAL 59

#define GATE_ICON_FRAME_HOVER 61

#define GATE_ICON_FRAME_PRESSED 60

#define GATE_TELEPORT_PRESS_TICKS 6 


#define MINIMAP_WINDOW_CONTENT_X 32

#define MINIMAP_WINDOW_CONTENT_Y 40

#define MINIMAP_WINDOW_CONTENT_W 288

#define MINIMAP_WINDOW_CONTENT_H 336

#define MINIMAP_WINDOW_PLAYER_X 160

#define MINIMAP_WINDOW_PLAYER_Y 210


#define INVENTORY_PANEL_X 335

#define INVENTORY_PANEL_Y 10

#define INVENTORY_PANEL_WIDTH 300

#define INVENTORY_PANEL_HEIGHT 380

#define INVENTORY_GRID_COLS 5

#define INVENTORY_GRID_ROWS 4

#define INVENTORY_GRID_CELL 35

#define INVENTORY_GRID_ORIGIN_X (INVENTORY_PANEL_X + 10)

#define INVENTORY_GRID_ORIGIN_Y (INVENTORY_PANEL_Y + 220)


#define INVENTORY_WINDOW_X 320

#define INVENTORY_WINDOW_Y 0

#define INVENTORY_WINDOW_WIDTH 320 

#define INVENTORY_WINDOW_HEIGHT 416

#define INVENTORY_BG_FRAME_LEFT 85

#define INVENTORY_BG_FRAME_GRID_EXT 86

#define INVENTORY_BG_FRAME_EQUIP_HEADER 83

#define INVENTORY_BG_FRAME_EQUIP_MALE 82

#define INVENTORY_BG_FRAME_EQUIP_FEMALE 87

#define INVENTORY_BG_FRAME_EQUIP_BORDER 84

#define INVENTORY_EQUIP_HEADER_HEIGHT 42 

#define INVENTORY_EQUIP_PANEL_WIDTH 100  


#define INVENTORY_REAL_GRID_COLS 9

#define INVENTORY_REAL_GRID_ROWS 4

#define INVENTORY_REAL_GRID_CELL 32

#define INVENTORY_REAL_GRID_ORIGIN_X 15

#define INVENTORY_REAL_GRID_ORIGIN_Y 263


#define ITEM_ICON_SHEET_COUNT 14


#define WEAPON_WORLD_SHEET_COUNT 12


#define ITEM_ICON_FRAME_ONE_HANDED 240 

#define ITEM_ICON_FRAME_TWO_HANDED 250 

#define ITEM_ICON_FRAME_RANGED 150     

#define ITEM_ICON_FRAME_STAFF 251      

#define ITEM_ICON_FRAME_ROD 89         

#define ITEM_ICON_FRAME_ARMOR 29       

#define ITEM_ICON_FRAME_SHIELD 45      


#define ITEM_ICON_FRAME_HELMET 9      

#define ITEM_ICON_FRAME_BOOTS 40      

#define ITEM_ICON_FRAME_ACCESSORY 204 

#define ITEM_ICON_FRAME_TABLET 80     

#define ITEM_ICON_FRAME_MISC 343      


#define ITEM_ICON_BOX_SIZE 30


#define STATUS_MAGIC_WINDOW_X 0

#define STATUS_MAGIC_WINDOW_Y 0

#define STATUS_MAGIC_WINDOW_WIDTH 320 

#define STATUS_MAGIC_WINDOW_HEIGHT 416

#define STATUS_MAGIC_FRAME_STATUS_TAB 114

#define STATUS_MAGIC_FRAME_MAGIC_TAB 115

#define STATUS_HP_VALUE_X 58

#define STATUS_HP_VALUE_Y 91


#define STATUS_CLASS_NAME_X 18

#define STATUS_CLASS_NAME_Y 48

#define STATUS_CLASS_BUTTON_X 14

#define STATUS_CLASS_BUTTON_Y 62

#define STATUS_CLASS_BUTTON_W 104

#define STATUS_CLASS_BUTTON_H 16

#define STATUS_FRAME_CLASS_HUNTER 42  

#define STATUS_FRAME_CLASS_WITCH 44   

#define STATUS_FRAME_CLASS_WIZARD 45  

#define STATUS_FRAME_CLASS_WARRIOR 46 


#define STATUS_MAGIC_TAB_ROW_HEIGHT 34

#define STATUS_MAGIC_TAB_SPLIT_X 174


#define PLAYER_OCCLUSION_PROBE_HALF_WIDTH 25

#define PLAYER_OCCLUSION_PROBE_HEIGHT 60

#define PLAYER_OCCLUSION_TRANS 500


#define OBL_FIELD5_GROUND_DECAL_BIT 32


#define GROUND_DECAL_DRAW_DEPTH (-1000000000L)


#define GATE_RUNE_CIRCLE_FIELD8 15


#define GATE_BODY_BASE_FIELD8 8


#define GATE_BODY_PATTERN_INDEX 0


#define GATE_HIGHLIGHT_FADE_TICKS 45 


#define GATE_TRIGGER_ZONE_MAX_DISTANCE 4000


#define GATE_LABEL_GAP_Y 190


#define GATE_RING_GAP_Y 140


#define GATE_RING_TICKS_PER_FRAME 4




#define TRANSPORT_CIRCLE_FRONT_DISTANCE_PX 46


#define TRANSPORT_CIRCLE_LAYER_INTERVAL_TICKS 9


#define TRANSPORT_CIRCLE_FALL_DURATION_TICKS 8

#define TRANSPORT_CIRCLE_FALL_HEIGHT_PX 44


#define TRANSPORT_CIRCLE_BURST_PERIOD_TICKS 120

#define TRANSPORT_CIRCLE_BURST_TICKS_PER_FRAME 2


#define TRANSPORT_CIRCLE_TRIGGER_RADIUS_PX 34


#define TRANSPORT_CIRCLE_LABEL_GAP_Y 30


#define TRANSPORT_CIRCLE_HOVER_RADIUS_PX 52


#define DARKNESS_PLAYER_LIGHT_FRAME 0 

#define DARKNESS_NPC_LIGHT_FRAME 3    

#define DARKNESS_ITEM_LIGHT_FRAME 1   


#define DARKNESS_AMBIENT_FLOOR 0


#define DARKNESS_INTENSITY_OFF 2000


#define DARKNESS_GLOW_FRAME DARKNESS_NPC_LIGHT_FRAME

#define DARKNESS_GLOW_STRENGTH 100


#define ITEM_WORLD_ICON_SIZE 40

#define ITEM_PICKUP_RADIUS_TILES 1


#define ITEM_DROP_DISTANCE_WORLD_UNITS 150


#define ITEM_DROP_FALL_TICKS 15          

#define ITEM_DROP_FALL_START_OFFSET_Y 40 


#define ITEM_JUMP_EFFECT_TICKS 12    

#define ITEM_JUMP_EFFECT_HEIGHT_Y 16 


#define INVENTORY_MAX 64


#define EQUIPMENT_ARMOR_SLOTS 4

#define EQUIPMENT_ACCESSORY_SLOTS 4


#define EQUIPMENT_SHIELD_SLOT_INDEX 2


#define EQUIPMENT_HELMET_SLOT_INDEX 0

#define EQUIPMENT_BODY_SLOT_INDEX 1

#define EQUIPMENT_BOOTS_SLOT_INDEX 3

#endif 
