plugins {
    id 'com.android.application'
}

android {
    namespace 'org.openshadowflare.game'
    compileSdk 35
    ndkVersion '27.0.12077973'

    defaultConfig {
        applicationId 'org.openshadowflare.game'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'

        ndk {
            def osfAbi = project.findProperty('osfAbi')
            if (osfAbi) {
                abiFilters osfAbi.toString()
            } else {
                abiFilters 'arm64-v8a', 'x86_64'
            }
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                arguments '-DBUILD_TESTING=OFF', '-DOPENSHADOWFLARE_BUILD_EXE=OFF'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('../../../CMakeLists.txt')
            version '4.1.2'
        }
    }
}
