/*
 * Decompiled from: o_RKC_DBFCONTROL.dll
 * Generated by Ghidra
 */

/*
 * Function: RKC_DBF
 * Address: 10001000
 */

/* public: __thiscall RKC_DBF::RKC_DBF(void) */

RKC_DBF * __thiscall RKC_DBF::RKC_DBF(RKC_DBF *this)

{
                    /* 0x1000  1  ??0RKC_DBF@@QAE@XZ */
  RKC_DIB::RKC_DIB((RKC_DIB *)(this + 8));
  *(undefined4 *)(this + 4) = 0;
  *(undefined4 *)this = 0;
  return this;
}



/*
 * Function: ~RKC_DBF
 * Address: 10001020
 */

/* public: __thiscall RKC_DBF::~RKC_DBF(void) */

void __thiscall RKC_DBF::~RKC_DBF(RKC_DBF *this)

{
  void *pvStack_c;
  undefined *puStack_8;
  undefined4 local_4;
  
                    /* 0x1020  3  ??1RKC_DBF@@QAE@XZ */
  puStack_8 = &LAB_10001fbc;
  pvStack_c = ExceptionList;
  local_4 = 0;
  ExceptionList = &pvStack_c;
  Release(this);
  local_4 = 0xffffffff;
  RKC_DIB::~RKC_DIB((RKC_DIB *)(this + 8));
  ExceptionList = pvStack_c;
  return;
}



/*
 * Function: Release
 * Address: 10001070
 */

/* public: void __thiscall RKC_DBF::Release(void) */

void __thiscall RKC_DBF::Release(RKC_DBF *this)

{
                    /* 0x1070  34  ?Release@RKC_DBF@@QAEXXZ */
  RKC_DIB::Release((RKC_DIB *)(this + 8));
  *(undefined4 *)(this + 4) = 0;
  *(undefined4 *)this = 0;
  return;
}



/*
 * Function: GetDIBitmap
 * Address: 10001090
 */

/* public: class RKC_DIB * __thiscall RKC_DBF::GetDIBitmap(void) */

RKC_DIB * __thiscall RKC_DBF::GetDIBitmap(RKC_DBF *this)

{
                    /* 0x1090  19  ?GetDIBitmap@RKC_DBF@@QAEPAVRKC_DIB@@XZ */
  return (RKC_DIB *)(this + 8);
}



/*
 * Function: Draw
 * Address: 100010a0
 */

/* public: void __thiscall RKC_DBF::Draw(void) */

void __thiscall RKC_DBF::Draw(RKC_DBF *this)

{
                    /* 0x10a0  9  ?Draw@RKC_DBF@@QAEXXZ */
  RKC_UPDIB::Render(*(RKC_UPDIB **)this,(RKC_DIB *)(this + 8),*(long *)(this + 4),0,0,0,
                    (tagRECT *)(this + 0x14));
  return;
}



/*
 * Function: Flush
 * Address: 100010c0
 */

/* public: void __thiscall RKC_DBF::Flush(void) */

void __thiscall RKC_DBF::Flush(RKC_DBF *this)

{
                    /* 0x10c0  14  ?Flush@RKC_DBF@@QAEXXZ */
  RKC_UPDIB::FlushVSBlock(*(RKC_UPDIB **)this,*(long *)(this + 4));
  return;
}



/*
 * Function: GetVSBlockNo
 * Address: 100010d0
 */

/* public: long __thiscall RKC_DBF::GetVSBlockNo(void) */

long __thiscall RKC_DBF::GetVSBlockNo(RKC_DBF *this)

{
                    /* 0x10d0  29  ?GetVSBlockNo@RKC_DBF@@QAEJXZ */
  return *(long *)(this + 4);
}



/*
 * Function: SetClipRect
 * Address: 100010e0
 */

/* public: void __thiscall RKC_DBF::SetClipRect(struct tagRECT *) */

void __thiscall RKC_DBF::SetClipRect(RKC_DBF *this,tagRECT *param_1)

{
                    /* 0x10e0  36  ?SetClipRect@RKC_DBF@@QAEXPAUtagRECT@@@Z */
  *(undefined4 *)(this + 0x14) = *(undefined4 *)param_1;
  *(undefined4 *)(this + 0x18) = *(undefined4 *)(param_1 + 4);
  *(undefined4 *)(this + 0x1c) = *(undefined4 *)(param_1 + 8);
  *(undefined4 *)(this + 0x20) = *(undefined4 *)(param_1 + 0xc);
  return;
}



/*
 * Function: GetClipRect
 * Address: 10001100
 */

/* public: void __thiscall RKC_DBF::GetClipRect(struct tagRECT *) */

void __thiscall RKC_DBF::GetClipRect(RKC_DBF *this,tagRECT *param_1)

{
                    /* 0x1100  16  ?GetClipRect@RKC_DBF@@QAEXPAUtagRECT@@@Z */
  *(undefined4 *)param_1 = *(undefined4 *)(this + 0x14);
  *(undefined4 *)(param_1 + 4) = *(undefined4 *)(this + 0x18);
  *(undefined4 *)(param_1 + 8) = *(undefined4 *)(this + 0x1c);
  *(undefined4 *)(param_1 + 0xc) = *(undefined4 *)(this + 0x20);
  return;
}



/*
 * Function: operator=
 * Address: 10001120
 */

/* public: class RKC_DBF & __thiscall RKC_DBF::operator=(class RKC_DBF const &) */

RKC_DBF * __thiscall RKC_DBF::operator=(RKC_DBF *this,RKC_DBF *param_1)

{
  int iVar1;
  RKC_DBF *pRVar2;
  
                    /* 0x1120  5  ??4RKC_DBF@@QAEAAV0@ABV0@@Z */
  pRVar2 = this;
  for (iVar1 = 9; iVar1 != 0; iVar1 = iVar1 + -1) {
    *(undefined4 *)pRVar2 = *(undefined4 *)param_1;
    param_1 = param_1 + 4;
    pRVar2 = pRVar2 + 4;
  }
  return this;
}



/*
 * Function: operator=
 * Address: 10001140
 */

/* public: class RKC_DBFCONTROL & __thiscall RKC_DBFCONTROL::operator=(class RKC_DBFCONTROL const &)
    */

RKC_DBFCONTROL * __thiscall RKC_DBFCONTROL::operator=(RKC_DBFCONTROL *this,RKC_DBFCONTROL *param_1)

{
  int iVar1;
  RKC_DBFCONTROL *pRVar2;
  
                    /* 0x1140  6  ??4RKC_DBFCONTROL@@QAEAAV0@ABV0@@Z */
  pRVar2 = this;
  for (iVar1 = 0x51; iVar1 != 0; iVar1 = iVar1 + -1) {
    *(undefined4 *)pRVar2 = *(undefined4 *)param_1;
    param_1 = param_1 + 4;
    pRVar2 = pRVar2 + 4;
  }
  return this;
}



/*
 * Function: RKC_DBFCONTROL
 * Address: 10001160
 */

/* public: __thiscall RKC_DBFCONTROL::RKC_DBFCONTROL(void) */

RKC_DBFCONTROL * __thiscall RKC_DBFCONTROL::RKC_DBFCONTROL(RKC_DBFCONTROL *this)

{
  HANDLE pvVar1;
  
                    /* 0x1160  2  ??0RKC_DBFCONTROL@@QAE@XZ */
  FUN_10001cc0(this + 0x20,0x24,2,RKC_DBF::RKC_DBF);
  *(undefined4 *)(this + 0xc) = 0;
  *(undefined4 *)(this + 4) = 0;
  *(undefined4 *)(this + 0x128) = 0;
  *(undefined4 *)(this + 300) = 0;
  *(undefined4 *)(this + 0x130) = 0;
  *(undefined4 *)this = 0;
  *(undefined4 *)(this + 4) = 0;
  *(undefined4 *)(this + 8) = 0;
  *(undefined4 *)(this + 0x10) = 0;
  *(undefined4 *)(this + 0x78) = 0;
  *(undefined4 *)(this + 0x120) = 0x280;
  *(undefined4 *)(this + 0x124) = 0x1e0;
  *(undefined4 *)(this + 0x138) = 0;
  *(undefined4 *)(this + 0x88) = 0;
  *(undefined4 *)(this + 0x140) = 0;
  *(undefined4 *)(this + 0x84) = 0;
  *(undefined4 *)(this + 0x74) = 0;
  *(undefined4 *)(this + 0x14) = 0;
  pvVar1 = CreateMutexA((LPSECURITY_ATTRIBUTES)0x0,0,(LPCSTR)0x0);
  *(HANDLE *)(this + 0x13c) = pvVar1;
  return this;
}



/*
 * Function: Release
 * Address: 100011f0
 */

/* public: void __thiscall RKC_DBFCONTROL::Release(void) */

void __thiscall RKC_DBFCONTROL::Release(RKC_DBFCONTROL *this)

{
  int *piVar1;
  
                    /* 0x11f0  35  ?Release@RKC_DBFCONTROL@@QAEXXZ */
  if (*(HANDLE *)(this + 0x74) != (HANDLE)0x0) {
    CloseHandle(*(HANDLE *)(this + 0x74));
    *(undefined4 *)(this + 0x74) = 0;
  }
  if (*(HANDLE *)(this + 0x84) != (HANDLE)0x0) {
    CloseHandle(*(HANDLE *)(this + 0x84));
    *(undefined4 *)(this + 0x84) = 0;
  }
  if (*(UINT *)(this + 0x78) != 0) {
    timeKillEvent(*(UINT *)(this + 0x78));
  }
  *(undefined4 *)(this + 0x78) = 0;
  if (*(int *)(this + 0x128) != 0) {
    piVar1 = *(int **)(this + 300);
    if (piVar1 != (int *)0x0) {
      (**(code **)(*piVar1 + 8))(piVar1);
    }
    (**(code **)(**(int **)(this + 0x128) + 8))(*(int **)(this + 0x128));
    *(undefined4 *)(this + 0x128) = 0;
  }
  if (*(HGDIOBJ *)(this + 0x140) != (HGDIOBJ)0x0) {
    DeleteObject(*(HGDIOBJ *)(this + 0x140));
    *(undefined4 *)(this + 0x140) = 0;
  }
  return;
}



/*
 * Function: ~RKC_DBFCONTROL
 * Address: 10001280
 */

/* public: __thiscall RKC_DBFCONTROL::~RKC_DBFCONTROL(void) */

void __thiscall RKC_DBFCONTROL::~RKC_DBFCONTROL(RKC_DBFCONTROL *this)

{
  void *pvStack_c;
  undefined *puStack_8;
  undefined4 local_4;
  
                    /* 0x1280  4  ??1RKC_DBFCONTROL@@QAE@XZ */
  puStack_8 = &LAB_10001fe6;
  pvStack_c = ExceptionList;
  local_4 = 0;
  ExceptionList = &pvStack_c;
  Release(this);
  CloseHandle(*(HANDLE *)(this + 0x13c));
  local_4 = 0xffffffff;
  FUN_10001d42(this + 0x20,0x24,2,RKC_DBF::~RKC_DBF);
  ExceptionList = pvStack_c;
  return;
}



/*
 * Function: Initialize
 * Address: 100012f0
 */

/* public: int __thiscall RKC_DBFCONTROL::Initialize(struct HWND__ *,class RKC_UPDIB
   *,long,long,long,int (__cdecl*)(void),long,long,struct tagRECT *,int,struct tagRGBQUAD *,long) */

int __thiscall
RKC_DBFCONTROL::Initialize
          (RKC_DBFCONTROL *this,HWND__ *param_1,RKC_UPDIB *param_2,long param_3,long param_4,
          long param_5,_func_int *param_6,long param_7,long param_8,tagRECT *param_9,int param_10,
          tagRGBQUAD *param_11,long param_12)

{
  RKC_DBFCONTROL *pRVar1;
  int *piVar2;
  int iVar3;
  HDC hdc;
  HBITMAP pHVar4;
  int **ppiVar5;
  int *apiStack_94 [2];
  undefined4 auStack_20 [6];
  undefined4 uStack_8;
  
                    /* 0x12f0  31
                       ?Initialize@RKC_DBFCONTROL@@QAEHPAUHWND__@@PAVRKC_UPDIB@@JJJP6AHXZJJPAUtagRECT@@HPAUtagRGBQUAD@@J@Z
                        */
  *(HWND__ **)(this + 0x1c) = param_1;
  *(RKC_UPDIB **)(this + 0x20) = param_2;
  *(RKC_UPDIB **)(this + 0x44) = param_2;
  *(_func_int **)(this + 0x134) = param_6;
  *(long *)(this + 0x24) = param_3;
  *(long *)(this + 0x48) = param_4;
  apiStack_94[1] = (int *)0x1000134a;
  RKC_DIB::Create((RKC_DIB *)(this + 0x28),param_7,param_8,0x18,1);
  apiStack_94[1] = (int *)0x10001355;
  RKC_DIB::Create((RKC_DIB *)(this + 0x4c),param_7,param_8,0x18,1);
  *(long *)(this + 0x120) = param_7;
  *(long *)(this + 0x124) = param_8;
  *(undefined4 *)(this + 0x34) = *(undefined4 *)param_9;
  *(undefined4 *)(this + 0x38) = *(undefined4 *)(param_9 + 4);
  *(undefined4 *)(this + 0x3c) = *(undefined4 *)(param_9 + 8);
  *(undefined4 *)(this + 0x40) = *(undefined4 *)(param_9 + 0xc);
  *(undefined4 *)(this + 0x58) = *(undefined4 *)param_9;
  *(undefined4 *)(this + 0x5c) = *(undefined4 *)(param_9 + 4);
  *(undefined4 *)(this + 0x60) = *(undefined4 *)(param_9 + 8);
  *(undefined4 *)(this + 100) = *(undefined4 *)(param_9 + 0xc);
  *(int *)(this + 0x7c) = param_10;
  if (param_11 == (tagRGBQUAD *)0x0) {
    *(undefined4 *)(this + 0x80) = 0;
  }
  else {
    *(undefined4 *)(this + 0x80) = *(undefined4 *)param_11;
  }
  *(long *)(this + 0x6c) = param_5;
  if (param_5 == 0) {
    pRVar1 = this + 0x128;
    iVar3 = DirectDrawCreate();
    if (iVar3 != 0) {
      return 0;
    }
    apiStack_94[0] = *(int **)pRVar1;
    apiStack_94[1] = (int *)uStack_8;
    iVar3 = (**(code **)(*apiStack_94[0] + 0x50))();
    if (iVar3 != 0) {
      return 0;
    }
    iVar3 = (**(code **)(**(int **)pRVar1 + 0x54))
                      (*(int **)pRVar1,*(undefined4 *)(this + 0x120),*(undefined4 *)(this + 0x124),
                       0x10);
    if (iVar3 != 0) {
      return 0;
    }
    ppiVar5 = apiStack_94;
    for (iVar3 = 0x1b; iVar3 != 0; iVar3 = iVar3 + -1) {
      *ppiVar5 = (int *)0x0;
      ppiVar5 = ppiVar5 + 1;
    }
    apiStack_94[0] = (int *)0x6c;
    apiStack_94[1] = (int *)0x21;
    iVar3 = (**(code **)(**(int **)pRVar1 + 0x18))(*(int **)pRVar1,apiStack_94,this + 300,0);
    if (iVar3 != 0) {
      return 0;
    }
    piVar2 = *(int **)(this + 300);
    auStack_20[0] = 4;
    iVar3 = (**(code **)(*piVar2 + 0x30))(piVar2,auStack_20,this + 0x130);
    if (iVar3 != 0) {
      return 0;
    }
  }
  else {
    hdc = GetDC(*(HWND *)(this + 0x1c));
    pHVar4 = CreateCompatibleBitmap(hdc,*(int *)(this + 0x120),*(int *)(this + 0x124));
    *(HBITMAP *)(this + 0x140) = pHVar4;
    ReleaseDC(*(HWND *)(this + 0x1c),hdc);
  }
  return 1;
}



/*
 * Function: GetCurrentDBF
 * Address: 10001520
 */

/* public: class RKC_DBF * __thiscall RKC_DBFCONTROL::GetCurrentDBF(void) */

RKC_DBF * __thiscall RKC_DBFCONTROL::GetCurrentDBF(RKC_DBFCONTROL *this)

{
                    /* 0x1520  18  ?GetCurrentDBF@RKC_DBFCONTROL@@QAEPAVRKC_DBF@@XZ */
  return (RKC_DBF *)(this + *(int *)(this + 0xc) * 0x24 + 0x20);
}



/*
 * Function: GetDrawingFlag
 * Address: 10001530
 */

/* public: int __thiscall RKC_DBFCONTROL::GetDrawingFlag(void) */

int __thiscall RKC_DBFCONTROL::GetDrawingFlag(RKC_DBFCONTROL *this)

{
  int iVar1;
  
                    /* 0x1530  22  ?GetDrawingFlag@RKC_DBFCONTROL@@QAEHXZ */
  WaitForSingleObject(*(HANDLE *)(this + 0x13c),0xffffffff);
  iVar1 = *(int *)(this + 4);
  ReleaseMutex(*(HANDLE *)(this + 0x13c));
  return iVar1;
}



/*
 * Function: Redraw
 * Address: 10001560
 */

/* public: int __thiscall RKC_DBFCONTROL::Redraw(void) */

int __thiscall RKC_DBFCONTROL::Redraw(RKC_DBFCONTROL *this)

{
  int iVar1;
  
                    /* 0x1560  33  ?Redraw@RKC_DBFCONTROL@@QAEHXZ */
  iVar1 = GetDrawingFlag(this);
  if ((iVar1 != 1) && (*(int *)(this + 0x14) == 0)) {
    *(int *)(this + 0xc) = 1 - *(int *)(this + 0xc);
    WaitForSingleObject(*(HANDLE *)(this + 0x13c),0xffffffff);
    *(undefined4 *)(this + 4) = 1;
    ReleaseMutex(*(HANDLE *)(this + 0x13c));
    *(undefined4 *)(this + 0x14) = 1;
  }
  RKC_DBF::Flush((RKC_DBF *)(this + *(int *)(this + 0xc) * 0x24 + 0x20));
  return 1;
}



/*
 * Function: Draw
 * Address: 100015d0
 */

/* public: class RKC_DIB * __thiscall RKC_DBFCONTROL::Draw(void) */

RKC_DIB * __thiscall RKC_DBFCONTROL::Draw(RKC_DBFCONTROL *this)

{
                    /* 0x15d0  10  ?Draw@RKC_DBFCONTROL@@QAEPAVRKC_DIB@@XZ */
  if (*(int *)(this + 0x7c) == 1) {
    RKC_DIB::Fill((RKC_DIB *)(this + *(int *)(this + 0xc) * -0x24 + 0x4c),
                  (uint)CONCAT21(CONCAT11(this[0x80],this[0x81]),this[0x82]));
  }
  RKC_DBF::Draw((RKC_DBF *)(this + *(int *)(this + 0xc) * -0x24 + 0x44));
  return (RKC_DIB *)(this + *(int *)(this + 0xc) * -0x24 + 0x4c);
}



/*
 * Function: DrawEnd
 * Address: 10001640
 */

/* public: void __thiscall RKC_DBFCONTROL::DrawEnd(void) */

void __thiscall RKC_DBFCONTROL::DrawEnd(RKC_DBFCONTROL *this)

{
                    /* 0x1640  11  ?DrawEnd@RKC_DBFCONTROL@@QAEXXZ */
  WaitForSingleObject(*(HANDLE *)(this + 0x13c),0xffffffff);
  *(int *)(this + 0x68) = *(int *)(this + 0x68) + 1;
  if (*(int *)(this + 4) == 1) {
    *(undefined4 *)(this + 4) = 0;
  }
  ReleaseMutex(*(HANDLE *)(this + 0x13c));
  return;
}



/*
 * Function: FlushDrawCount
 * Address: 10001680
 */

/* public: void __thiscall RKC_DBFCONTROL::FlushDrawCount(void) */

void __thiscall RKC_DBFCONTROL::FlushDrawCount(RKC_DBFCONTROL *this)

{
                    /* 0x1680  15  ?FlushDrawCount@RKC_DBFCONTROL@@QAEXXZ */
  *(undefined4 *)(this + 0x68) = 0;
  return;
}



/*
 * Function: GetDrawCount
 * Address: 10001690
 */

/* public: long __thiscall RKC_DBFCONTROL::GetDrawCount(void) */

long __thiscall RKC_DBFCONTROL::GetDrawCount(RKC_DBFCONTROL *this)

{
                    /* 0x1690  20  ?GetDrawCount@RKC_DBFCONTROL@@QAEJXZ */
  return *(long *)(this + 0x68);
}



/*
 * Function: Paint
 * Address: 100016a0
 */

/* public: void __thiscall RKC_DBFCONTROL::Paint(struct HDC__ *,int) */

void __thiscall RKC_DBFCONTROL::Paint(RKC_DBFCONTROL *this,HDC__ *param_1,int param_2)

{
  int *piVar1;
  RKC_DIB *this_00;
  int iVar2;
  HDC hdc;
  HDC__ *unaff_EDI;
  
                    /* 0x16a0  32  ?Paint@RKC_DBFCONTROL@@QAEXPAUHDC__@@H@Z */
  if (*(int *)this == 1) {
    this_00 = RKC_DBF::GetDIBitmap((RKC_DBF *)(this + *(int *)(this + 0xc) * -0x24 + 0x44));
    if (this_00 != (RKC_DIB *)0x0) {
      if (*(int *)(this + 0x6c) == 0) {
        piVar1 = *(int **)(this + 0x130);
        if (piVar1 != (int *)0x0) {
          if (param_2 == 0) {
            iVar2 = (**(code **)(*piVar1 + 0x60))(piVar1);
            if (iVar2 == -0x7789fe3e) {
              (**(code **)(**(int **)(this + 0x130) + 0x6c))(*(int **)(this + 0x130));
            }
            (**(code **)(**(int **)(this + 0x130) + 0x44))(*(int **)(this + 0x130),&stack0xfffffff8)
            ;
            RKC_DIB::TransferToDDB(this_00,unaff_EDI,0,0);
            if (*(code **)(this + 0x138) != (code *)0x0) {
              (**(code **)(this + 0x138))(unaff_EDI);
            }
            (**(code **)(**(int **)(this + 0x130) + 0x68))(*(int **)(this + 0x130),unaff_EDI);
            iVar2 = (**(code **)(**(int **)(this + 300) + 0x2c))(*(int **)(this + 300),0,1);
            if (iVar2 == -0x7789fe3e) {
              (**(code **)(**(int **)(this + 300) + 0x6c))(*(int **)(this + 300));
              DrawEnd(this);
              return;
            }
          }
          else {
            (**(code **)(**(int **)(this + 0x128) + 0x28))(*(int **)(this + 0x128));
            RKC_DIB::TransferToDDB(this_00,param_1,0,0);
            if (*(code **)(this + 0x138) != (code *)0x0) {
              (**(code **)(this + 0x138))(param_1);
              DrawEnd(this);
              return;
            }
          }
        }
      }
      else {
        hdc = CreateCompatibleDC(param_1);
        SelectObject(hdc,*(HGDIOBJ *)(this + 0x140));
        RKC_DIB::TransferToDDB(this_00,hdc,0,0);
        if (*(code **)(this + 0x138) != (code *)0x0) {
          (**(code **)(this + 0x138))(hdc);
        }
        BitBlt(param_1,0,0,*(int *)(this + 0x120),*(int *)(this + 0x124),hdc,0,0,0xcc0020);
        DeleteDC(hdc);
      }
    }
  }
  DrawEnd(this);
  return;
}



/*
 * Function: SetPaintFunction
 * Address: 10001850
 */

/* public: void __thiscall RKC_DBFCONTROL::SetPaintFunction(void (__cdecl*)(struct HDC__ *)) */

void __thiscall RKC_DBFCONTROL::SetPaintFunction(RKC_DBFCONTROL *this,_func_void_HDC___ptr *param_1)

{
                    /* 0x1850  38  ?SetPaintFunction@RKC_DBFCONTROL@@QAEXP6AXPAUHDC__@@@Z@Z */
  *(_func_void_HDC___ptr **)(this + 0x138) = param_1;
  return;
}



/*
 * Function: GetStyle
 * Address: 10001860
 */

/* public: long __thiscall RKC_DBFCONTROL::GetStyle(long) */

long __thiscall RKC_DBFCONTROL::GetStyle(RKC_DBFCONTROL *this,long param_1)

{
                    /* 0x1860  26  ?GetStyle@RKC_DBFCONTROL@@QAEJJ@Z */
  if (param_1 == -1) {
    param_1 = *(long *)(this + 0x6c);
  }
  return (-(uint)(param_1 != 1) & 0x7f360000) + 0xca0000;
}



/*
 * Function: GetExStyle
 * Address: 10001880
 */

/* public: long __thiscall RKC_DBFCONTROL::GetExStyle(long) */

long __thiscall RKC_DBFCONTROL::GetExStyle(RKC_DBFCONTROL *this,long param_1)

{
                    /* 0x1880  23  ?GetExStyle@RKC_DBFCONTROL@@QAEJJ@Z */
  if (param_1 == -1) {
    param_1 = *(long *)(this + 0x6c);
  }
  return (-(uint)(param_1 != 1) & 0xfffffff8) + 0x10;
}



/*
 * Function: GetPosition
 * Address: 100018a0
 */

/* public: struct tagPOINT __thiscall RKC_DBFCONTROL::GetPosition(long) */

void __thiscall RKC_DBFCONTROL::GetPosition(RKC_DBFCONTROL *this,undefined4 *param_1,int param_2)

{
                    /* 0x18a0  25  ?GetPosition@RKC_DBFCONTROL@@QAE?AUtagPOINT@@J@Z */
  if (param_2 == -1) {
    param_2 = *(int *)(this + 0x6c);
  }
  if (param_2 == 1) {
    *param_1 = 0x80000000;
    param_1[1] = 0x80000000;
    return;
  }
  *param_1 = 0;
  param_1[1] = 0;
  return;
}



/*
 * Function: SetClipRect
 * Address: 100018e0
 */

/* public: void __thiscall RKC_DBFCONTROL::SetClipRect(struct tagRECT *) */

void __thiscall RKC_DBFCONTROL::SetClipRect(RKC_DBFCONTROL *this,tagRECT *param_1)

{
                    /* 0x18e0  37  ?SetClipRect@RKC_DBFCONTROL@@QAEXPAUtagRECT@@@Z */
  *(undefined4 *)(this + 0x34) = *(undefined4 *)param_1;
  *(undefined4 *)(this + 0x38) = *(undefined4 *)(param_1 + 4);
  *(undefined4 *)(this + 0x3c) = *(undefined4 *)(param_1 + 8);
  *(undefined4 *)(this + 0x40) = *(undefined4 *)(param_1 + 0xc);
  *(undefined4 *)(this + 0x58) = *(undefined4 *)param_1;
  *(undefined4 *)(this + 0x5c) = *(undefined4 *)(param_1 + 4);
  *(undefined4 *)(this + 0x60) = *(undefined4 *)(param_1 + 8);
  *(undefined4 *)(this + 100) = *(undefined4 *)(param_1 + 0xc);
  return;
}



/*
 * Function: GetClipRect
 * Address: 10001920
 */

/* public: void __thiscall RKC_DBFCONTROL::GetClipRect(struct tagRECT *,long) */

void __thiscall RKC_DBFCONTROL::GetClipRect(RKC_DBFCONTROL *this,tagRECT *param_1,long param_2)

{
  RKC_DBFCONTROL *pRVar1;
  
                    /* 0x1920  17  ?GetClipRect@RKC_DBFCONTROL@@QAEXPAUtagRECT@@J@Z */
  pRVar1 = this + param_2 * 0x24 + 0x34;
  *(undefined4 *)param_1 = *(undefined4 *)pRVar1;
  *(undefined4 *)(param_1 + 4) = *(undefined4 *)(pRVar1 + 4);
  *(undefined4 *)(param_1 + 8) = *(undefined4 *)(pRVar1 + 8);
  *(undefined4 *)(param_1 + 0xc) = *(undefined4 *)(pRVar1 + 0xc);
  return;
}



/*
 * Function: DisableDraw
 * Address: 10001950
 */

/* public: void __thiscall RKC_DBFCONTROL::DisableDraw(void) */

void __thiscall RKC_DBFCONTROL::DisableDraw(RKC_DBFCONTROL *this)

{
  int iVar1;
  
                    /* 0x1950  8  ?DisableDraw@RKC_DBFCONTROL@@QAEXXZ */
  *(undefined4 *)this = 0;
  iVar1 = GetDrawingFlag(this);
  while (iVar1 == 1) {
    Sleep(1);
    iVar1 = GetDrawingFlag(this);
  }
  return;
}



/*
 * Function: EnableDraw
 * Address: 10001980
 */

/* public: void __thiscall RKC_DBFCONTROL::EnableDraw(void) */

void __thiscall RKC_DBFCONTROL::EnableDraw(RKC_DBFCONTROL *this)

{
                    /* 0x1980  13  ?EnableDraw@RKC_DBFCONTROL@@QAEXXZ */
  *(undefined4 *)this = 1;
  return;
}



/*
 * Function: StopAll
 * Address: 10001990
 */

/* public: void __thiscall RKC_DBFCONTROL::StopAll(void) */

void __thiscall RKC_DBFCONTROL::StopAll(RKC_DBFCONTROL *this)

{
  int iVar1;
  
                    /* 0x1990  41  ?StopAll@RKC_DBFCONTROL@@QAEXXZ */
  if (*(int *)(this + 8) == 1) {
    *(undefined4 *)(this + 0x18) = 0;
    *(undefined4 *)(this + 8) = 0;
    iVar1 = *(int *)(this + 0x18);
    while (iVar1 == 0) {
      Sleep(1);
      iVar1 = *(int *)(this + 0x18);
    }
    SuspendThread(*(HANDLE *)(this + 0x74));
    iVar1 = *(int *)(this + 0x14);
    while (iVar1 == 1) {
      Sleep(1);
      iVar1 = *(int *)(this + 0x14);
    }
    SuspendThread(*(HANDLE *)(this + 0x84));
    if (*(HANDLE *)(this + 0x74) != (HANDLE)0x0) {
      CloseHandle(*(HANDLE *)(this + 0x74));
      *(undefined4 *)(this + 0x74) = 0;
    }
    DisableDraw(this);
  }
  return;
}



/*
 * Function: StartAll
 * Address: 10001a10
 */

/* public: void __thiscall RKC_DBFCONTROL::StartAll(void) */

void __thiscall RKC_DBFCONTROL::StartAll(RKC_DBFCONTROL *this)

{
  HANDLE pvVar1;
  MMRESULT MVar2;
  RKC_DBFCONTROL *local_4;
  
                    /* 0x1a10  40  ?StartAll@RKC_DBFCONTROL@@QAEXXZ */
  if (*(int *)(this + 8) == 0) {
    local_4 = this;
    if (*(int *)(this + 0x74) == 0) {
      pvVar1 = CreateThread((LPSECURITY_ATTRIBUTES)0x0,0,FUN_10001bd0,this,4,(LPDWORD)&local_4);
      *(HANDLE *)(this + 0x74) = pvVar1;
      SetThreadPriority(pvVar1,2);
      ResumeThread(*(HANDLE *)(this + 0x74));
    }
    if (*(int *)(this + 0x84) == 0) {
      pvVar1 = CreateThread((LPSECURITY_ATTRIBUTES)0x0,0,(LPTHREAD_START_ROUTINE)&LAB_10001c60,this,
                            4,(LPDWORD)&local_4);
      *(HANDLE *)(this + 0x84) = pvVar1;
      ResumeThread(pvVar1);
    }
    if (*(int *)(this + 0x78) == 0) {
      MVar2 = timeSetEvent(1,1,&LAB_10001c50,(DWORD_PTR)this,1);
      *(MMRESULT *)(this + 0x78) = MVar2;
    }
    EnableDraw(this);
    *(undefined4 *)(this + 8) = 1;
  }
  return;
}



/*
 * Function: GetFramePerSecond
 * Address: 10001ab0
 */

/* public: long __thiscall RKC_DBFCONTROL::GetFramePerSecond(void) */

long __thiscall RKC_DBFCONTROL::GetFramePerSecond(RKC_DBFCONTROL *this)

{
                    /* 0x1ab0  24  ?GetFramePerSecond@RKC_DBFCONTROL@@QAEJXZ */
  return *(long *)(this + 0x70);
}



/*
 * Function: Clear
 * Address: 10001ac0
 */

/* public: int __thiscall RKC_DBFCONTROL::Clear(struct tagRGBQUAD *) */

int __thiscall RKC_DBFCONTROL::Clear(RKC_DBFCONTROL *this,tagRGBQUAD *param_1)

{
                    /* 0x1ac0  7  ?Clear@RKC_DBFCONTROL@@QAEHPAUtagRGBQUAD@@@Z */
  if (param_1 != (tagRGBQUAD *)0x0) {
    RKC_DIB::Fill((RKC_DIB *)(this + 0x28),(uint)CONCAT21(CONCAT11(*param_1,param_1[1]),param_1[2]))
    ;
    RKC_DIB::Fill((RKC_DIB *)(this + 0x4c),(uint)CONCAT21(CONCAT11(*param_1,param_1[1]),param_1[2]))
    ;
    return 1;
  }
  RKC_DIB::FillByte((RKC_DIB *)(this + 0x28),'\0');
  RKC_DIB::FillByte((RKC_DIB *)(this + 0x4c),'\0');
  return 1;
}



/*
 * Function: SetScreenClear
 * Address: 10001b30
 */

/* public: void __thiscall RKC_DBFCONTROL::SetScreenClear(int,struct tagRGBQUAD *) */

void __thiscall RKC_DBFCONTROL::SetScreenClear(RKC_DBFCONTROL *this,int param_1,tagRGBQUAD *param_2)

{
                    /* 0x1b30  39  ?SetScreenClear@RKC_DBFCONTROL@@QAEXHPAUtagRGBQUAD@@@Z */
  *(int *)(this + 0x7c) = param_1;
  if (param_2 != (tagRGBQUAD *)0x0) {
    *(undefined4 *)(this + 0x80) = *(undefined4 *)param_2;
    return;
  }
  *(undefined4 *)(this + 0x80) = 0;
  return;
}



/*
 * Function: GetSurface
 * Address: 10001b60
 */

/* public: struct IDirectDrawSurface * __thiscall RKC_DBFCONTROL::GetSurface(int) */

IDirectDrawSurface * __thiscall RKC_DBFCONTROL::GetSurface(RKC_DBFCONTROL *this,int param_1)

{
                    /* 0x1b60  27  ?GetSurface@RKC_DBFCONTROL@@QAEPAUIDirectDrawSurface@@H@Z */
  if (param_1 != 0) {
    return *(IDirectDrawSurface **)(this + 300);
  }
  return *(IDirectDrawSurface **)(this + 0x130);
}



/*
 * Function: GetDrawThreadHandle
 * Address: 10001b80
 */

/* public: void * __thiscall RKC_DBFCONTROL::GetDrawThreadHandle(void) */

void * __thiscall RKC_DBFCONTROL::GetDrawThreadHandle(RKC_DBFCONTROL *this)

{
                    /* 0x1b80  21  ?GetDrawThreadHandle@RKC_DBFCONTROL@@QAEPAXXZ */
  return *(void **)(this + 0x84);
}



/*
 * Function: DrawFunction
 * Address: 10001b90
 */

/* public: void __thiscall RKC_DBFCONTROL::DrawFunction(void) */

void __thiscall RKC_DBFCONTROL::DrawFunction(RKC_DBFCONTROL *this)

{
                    /* 0x1b90  12  ?DrawFunction@RKC_DBFCONTROL@@QAEXXZ */
  if (*(int *)this == 1) {
    Draw(this);
  }
  *(undefined4 *)(this + 0x14) = 0;
  return;
}



/*
 * Function: GetWindowHandle
 * Address: 10001bb0
 */

/* public: struct HWND__ * __thiscall RKC_DBFCONTROL::GetWindowHandle(void) */

HWND__ * __thiscall RKC_DBFCONTROL::GetWindowHandle(RKC_DBFCONTROL *this)

{
                    /* 0x1bb0  30  ?GetWindowHandle@RKC_DBFCONTROL@@QAEPAUHWND__@@XZ */
  return *(HWND__ **)(this + 0x1c);
}



/*
 * Function: GetThreadDrawFlag
 * Address: 10001bc0
 */

/* public: int __thiscall RKC_DBFCONTROL::GetThreadDrawFlag(void) */

int __thiscall RKC_DBFCONTROL::GetThreadDrawFlag(RKC_DBFCONTROL *this)

{
                    /* 0x1bc0  28  ?GetThreadDrawFlag@RKC_DBFCONTROL@@QAEHXZ */
  return *(int *)(this + 0x14);
}



/*
 * Function: FUN_10001bd0
 * Address: 10001bd0
 */

void FUN_10001bd0(RKC_DBFCONTROL *param_1)

{
  RKC_DBFCONTROL *this;
  int iVar1;
  long lVar2;
  RKC_DBFCONTROL *pRVar3;
  
  this = param_1;
  pRVar3 = *(RKC_DBFCONTROL **)(param_1 + 0x10);
  param_1 = pRVar3;
  do {
    while (*(int *)(this + 8) != 1) {
      *(undefined4 *)(this + 0x18) = 1;
      Sleep(1);
    }
    iVar1 = (**(code **)(this + 0x134))();
    if (iVar1 == 1) {
      if (999 < *(int *)(this + 0x10) - (int)param_1) {
        param_1 = *(RKC_DBFCONTROL **)(this + 0x10);
        lVar2 = RKC_DBFCONTROL::GetDrawCount(this);
        *(long *)(this + 0x70) = lVar2;
        RKC_DBFCONTROL::FlushDrawCount(this);
      }
      RKC_DBFCONTROL::Redraw(this);
    }
    iVar1 = *(int *)(this + 0x10) - (int)pRVar3;
    while (iVar1 < 0x21) {
      Sleep(1);
      iVar1 = *(int *)(this + 0x10) - (int)pRVar3;
    }
    pRVar3 = *(RKC_DBFCONTROL **)(this + 0x10);
  } while( true );
}



/*
 * Function: DirectDrawCreate
 * Address: 10001cb0
 */

void DirectDrawCreate(void)

{
                    /* WARNING: Could not recover jumptable at 0x10001cb0. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  DirectDrawCreate();
  return;
}



/*
 * Function: FUN_10001cc0
 * Address: 10001cc0
 */

void FUN_10001cc0(undefined4 param_1,undefined4 param_2,int param_3,undefined *param_4)

{
  int local_20;
  void *local_14;
  undefined *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  puStack_c = &DAT_100020b8;
  puStack_10 = &DAT_10001f7e;
  local_14 = ExceptionList;
  local_8 = 0;
  ExceptionList = &local_14;
  for (local_20 = 0; local_20 < param_3; local_20 = local_20 + 1) {
    (*(code *)param_4)();
  }
  local_8 = 0xffffffff;
  FUN_10001d2a();
  ExceptionList = local_14;
  return;
}



/*
 * Function: FUN_10001d2a
 * Address: 10001d2a
 */

void FUN_10001d2a(void)

{
  int unaff_EBP;
  
  if (*(int *)(unaff_EBP + -0x20) == 0) {
    FUN_10001dc2(*(undefined4 *)(unaff_EBP + 8),*(undefined4 *)(unaff_EBP + 0xc),
                 *(int *)(unaff_EBP + -0x1c),*(undefined **)(unaff_EBP + 0x18));
  }
  return;
}



/*
 * Function: FUN_10001d42
 * Address: 10001d42
 */

void FUN_10001d42(undefined4 param_1,undefined4 param_2,int param_3,undefined *param_4)

{
  void *local_14;
  undefined *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  puStack_c = &DAT_100020c8;
  puStack_10 = &DAT_10001f7e;
  local_14 = ExceptionList;
  local_8 = 0;
  ExceptionList = &local_14;
  while( true ) {
    param_3 = param_3 + -1;
    if (param_3 < 0) break;
    (*(code *)param_4)();
  }
  local_8 = 0xffffffff;
  FUN_10001daa();
  ExceptionList = local_14;
  return;
}



/*
 * Function: FUN_10001daa
 * Address: 10001daa
 */

void FUN_10001daa(void)

{
  int unaff_EBP;
  
  if (*(int *)(unaff_EBP + -0x1c) == 0) {
    FUN_10001dc2(*(undefined4 *)(unaff_EBP + 8),*(undefined4 *)(unaff_EBP + 0xc),
                 *(int *)(unaff_EBP + 0x10),*(undefined **)(unaff_EBP + 0x14));
  }
  return;
}



/*
 * Function: FUN_10001dc2
 * Address: 10001dc2
 */

void FUN_10001dc2(undefined4 param_1,undefined4 param_2,int param_3,undefined *param_4)

{
  void *local_14;
  undefined *puStack_10;
  undefined *puStack_c;
  undefined4 local_8;
  
  puStack_c = &DAT_100020d8;
  puStack_10 = &DAT_10001f7e;
  local_14 = ExceptionList;
  local_8 = 0;
  ExceptionList = &local_14;
  while( true ) {
    param_3 = param_3 + -1;
    if (param_3 < 0) break;
    (*(code *)param_4)();
  }
  ExceptionList = local_14;
  return;
}



/*
 * Function: FUN_10001e20
 * Address: 10001e20
 */

int * __cdecl FUN_10001e20(undefined4 *param_1)

{
  int *piVar1;
  
  piVar1 = (int *)*param_1;
  if (*piVar1 != -0x1f928c9d) {
    return (int *)0x0;
  }
  terminate();
  return piVar1;
}



/*
 * Function: FUN_10001e36
 * Address: 10001e36
 */

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

undefined4 FUN_10001e36(undefined4 param_1,int param_2)

{
  undefined4 uVar1;
  undefined4 *_Memory;
  undefined4 *puVar2;
  
  if (param_2 == 0) {
    if (0 < DAT_10003010) {
      DAT_10003010 = DAT_10003010 + -1;
      goto LAB_10001e4c;
    }
LAB_10001e74:
    uVar1 = 0;
  }
  else {
LAB_10001e4c:
    _DAT_10003014 = *(undefined4 *)_adjust_fdiv_exref;
    if (param_2 == 1) {
      DAT_1000301c = (undefined4 *)malloc(0x80);
      if (DAT_1000301c == (undefined4 *)0x0) goto LAB_10001e74;
      *DAT_1000301c = 0;
      DAT_10003018 = DAT_1000301c;
      _initterm(&DAT_10003000,&DAT_10003004);
      DAT_10003010 = DAT_10003010 + 1;
    }
    else if ((param_2 == 0) &&
            (_Memory = DAT_1000301c, puVar2 = DAT_10003018, DAT_1000301c != (undefined4 *)0x0)) {
      while (puVar2 = puVar2 + -1, _Memory <= puVar2) {
        if ((code *)*puVar2 != (code *)0x0) {
          (*(code *)*puVar2)();
          _Memory = DAT_1000301c;
        }
      }
      free(_Memory);
      DAT_1000301c = (undefined4 *)0x0;
    }
    uVar1 = 1;
  }
  return uVar1;
}



/*
 * Function: entry
 * Address: 10001ee1
 */

int entry(HMODULE param_1,int param_2,undefined4 param_3)

{
  int iVar1;
  int iVar2;
  int iVar3;
  
  iVar1 = param_2;
  iVar2 = DAT_10003010;
  if (param_2 != 0) {
    if ((param_2 != 1) && (param_2 != 2)) goto LAB_10001f29;
    if ((DAT_10003020 != (code *)0x0) &&
       (iVar2 = (*DAT_10003020)(param_1,param_2,param_3), iVar2 == 0)) {
      return 0;
    }
    iVar2 = FUN_10001e36(param_1,param_2);
  }
  if (iVar2 == 0) {
    return 0;
  }
LAB_10001f29:
  iVar2 = FUN_10001f90(param_1,param_2);
  if (param_2 == 1) {
    if (iVar2 != 0) {
      return iVar2;
    }
    FUN_10001e36(param_1,0);
  }
  if ((param_2 != 0) && (param_2 != 3)) {
    return iVar2;
  }
  iVar3 = FUN_10001e36(param_1,param_2);
  param_2 = iVar2;
  if (iVar3 == 0) {
    param_2 = 0;
  }
  if (param_2 != 0) {
    if (DAT_10003020 != (code *)0x0) {
      iVar2 = (*DAT_10003020)(param_1,iVar1,param_3);
      return iVar2;
    }
    return param_2;
  }
  return 0;
}



/*
 * Function: terminate
 * Address: 10001f84
 */

void __cdecl terminate(void)

{
                    /* WARNING: Could not recover jumptable at 0x10001f84. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  terminate();
  return;
}



/*
 * Function: _initterm
 * Address: 10001f8a
 */

void _initterm(void)

{
                    /* WARNING: Could not recover jumptable at 0x10001f8a. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  _initterm();
  return;
}



/*
 * Function: FUN_10001f90
 * Address: 10001f90
 */

undefined4 FUN_10001f90(HMODULE param_1,int param_2)

{
  if ((param_2 == 1) && (DAT_10003020 == 0)) {
    DisableThreadLibraryCalls(param_1);
  }
  return 1;
}



/*
 * Function: Unwind@10001fb0
 * Address: 10001fb0
 */

void Unwind_10001fb0(void)

{
  int unaff_EBP;
  
                    /* WARNING: Could not recover jumptable at 0x10001fb6. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  RKC_DIB::~RKC_DIB((RKC_DIB *)(*(int *)(unaff_EBP + -0x10) + 8));
  return;
}



/*
 * Function: Unwind@10001fd0
 * Address: 10001fd0
 */

void Unwind_10001fd0(void)

{
  int unaff_EBP;
  
  FUN_10001d42(*(int *)(unaff_EBP + -0x10) + 0x20,0x24,2,RKC_DBF::~RKC_DBF);
  return;
}



